# -*- coding: utf-8 -*-
"""Proposed architecture: packages, layers, plugin contract, budgets."""

# name, layer, deps, size budget, what, why it is its own package
PACKAGES = [
 ("@oxygenui-design/grid-core", "L1 engine", [], "22 KB",
  "Row model pipeline, column model, sort · filter · selection · grouping · tree · aggregation, the query/page contract, view resolution, the keymap as data, and virtualisation <b>geometry</b> (not DOM).",
  "It is the part that must never change when a framework does. No DOM, no framework, no healthcare.", "P0"),
 ("@oxygenui-design/grid-signals", "L1 engine", ["grid-core"], "3 KB",
  "The reactivity substrate. A thin façade over a signals implementation so the core never imports one directly.",
  "TC39 Signals is Stage 1. When it lands, this is the only package that changes.", "P0"),
 ("@oxygenui-design/grid-dom", "L2 render", ["grid-core"], "18 KB",
  "The framework-free renderer: DOM construction, node recycling, scroll anchoring, focus management, the full ARIA contract, pointer and keyboard handling.",
  "<b>This is the decision that makes framework agnosticism affordable.</b> Accessibility and virtualisation are written once, not four times.", "P0"),
 ("@oxygenui-design/grid-react", "L3 adapter", ["grid-core", "grid-dom"], "4 KB",
  "React binding: hooks, portal-based cell renderers, Suspense-aware data source, SSR guidance.",
  "The reference adapter, and the only one shipped in wave one.", "P0"),
 ("@oxygenui-design/grid-angular", "L3 adapter", ["grid-core", "grid-dom"], "4 KB",
  "Angular binding over Angular signals.",
  "Wave two. Behavioural-health platforms skew Angular more than the React-first world assumes.", "P1"),
 ("@oxygenui-design/grid-vue", "L3 adapter", ["grid-core", "grid-dom"], "4 KB",
  "Vue binding over refs.", "Wave three, on evidence of demand.", "P2"),
 ("@oxygenui-design/grid-element", "L3 adapter", ["grid-core", "grid-dom"], "6 KB",
  "<code>&lt;ox-data-grid&gt;</code> custom element, light DOM only.",
  "The vanilla and Svelte/Qwik answer without a per-framework package. Light DOM deliberately: shadow DOM cuts the token cascade and forced-colors inheritance.", "P2"),
 ("@oxygenui-design/grid-healthcare", "L2 domain", ["grid-core", "grid-dom"], "16 KB",
  "Coverage, the absence taxonomy, identity safety, the disclosure policy, sort provenance, arrivals, the resolution cell, the cell host contract, and the fourteen recipes.",
  "<b>Separate so that generic logic cannot be contaminated by clinical assumptions</b>, and so a non-healthcare consumer pays nothing for it.", "P0"),
 ("@oxygenui-design/grid-fhir", "L2 domain", ["grid-healthcare", "fhir"], "9 KB",
  "Resource adapters, a <code>Bundle</code>-driven data source that follows <code>link.next</code>, search-parameter mapping, and honest handling of absent totals.",
  "FHIR is one interoperability profile among several. Baking it into the healthcare package would make an HL7v2 or CSV-fed customer pay for it.", "P1"),
 ("@oxygenui-design/grid-export", "L4 plugin", ["grid-core"], "7 KB",
  "CSV, XLSX and the print sheet — <b>with formula-injection defence as a non-optional part of the writer</b>.",
  "A plugin, because a read-only worklist should not ship an XLSX writer.", "P1"),
 ("@oxygenui-design/grid-filters", "L4 plugin", ["grid-core"], "8 KB",
  "The visual filter builder and the advanced condition editor.",
  "Most grids never show a builder.", "P1"),
 ("@oxygenui-design/grid-analytics", "L4 plugin", ["grid-core"], "5 KB + wasm",
  "The Arrow/DuckDB-WASM path: columnar ingest, in-browser SQL, facet counts without a round trip.",
  "Enormous, optional, and the only credible client-side answer above 100k rows. Never in core.", "P2"),
 ("@oxygenui-design/grid-ai", "L4 plugin", ["grid-core", "copilot-core"], "6 KB",
  "Natural-language → <code>FilterNode</code>, proposals, row summaries, anomaly lens.",
  "Optional by construction. AI must never be a dependency of a clinical list.", "P2"),
 ("@oxygenui-design/grid-testing", "tooling", ["grid-core"], "n/a",
  "Assertions that read a grid's accessibility tree, a deterministic fixture generator, and the performance harness.",
  "Matches the <code>tabs-testing</code> precedent. It is how customers assert their own grids are correct.", "P1"),
 ("@oxygenui-design/grid-devtools", "tooling", ["grid-core"], "n/a",
  "A panel that shows the action log, the resolved view, the active query, cache state and frame timings.",
  "<b>Debuggability is a product feature at this complexity.</b> No competitor ships one.", "P2"),
]

LAYERS = [
 ("L4", "Plugins", "export · filters · analytics · ai · clipboard · undo · charts",
  "Registered explicitly. Zero bytes when not imported."),
 ("L3", "Adapters", "react · angular · vue · element",
  "Thin. Bind framework reactivity to core signals and mount the DOM renderer. <b>No grid logic may live here</b> — an adapter with a feature in it is a bug."),
 ("L2", "Render + domain", "grid-dom · grid-healthcare · grid-fhir",
  "The DOM renderer is framework-free and owns accessibility. The healthcare layer owns clinical meaning and never leaks into core."),
 ("L1", "Engine", "grid-core · grid-signals",
  "Pure logic. No DOM, no framework, no clinical vocabulary. Testable without a renderer, which is what makes 40,000-row property tests cheap."),
 ("L0", "Foundation", "tokens · fhir types · intl · utils",
  "Already exists in OxygenUI and is reused, not re-created."),
]

# Plugin lifecycle hooks — deliberately small
HOOKS = [
 ("setup(ctx)", "once, at registration", "Register reducers, selectors, key bindings, column types, slots and commands.", "The only place a plugin may extend the type surface."),
 ("onAction(action, state)", "every action, before reduction", "Observe or veto. A veto must carry a reason that the grid can render.", "This is how the disclosure policy blocks a copy, and how audit sees everything."),
 ("selectors", "derived, memoised", "Contribute derived state — a facet count, an anomaly mark, an aggregate.", "Pull, never push. A plugin may not write into grid state directly."),
 ("slots", "render time", "Contribute UI into named regions: toolbar, header menu, row affix, footer, empty state.", "A fixed, documented set of ~12 regions. <b>Not arbitrary render injection</b> — that is how plugin systems become unmaintainable."),
 ("onQuery(query)", "before a server request", "Amend the outgoing query (add a facet, a projection, a hint).", "One hook, ordered by registration, with the composed result logged."),
 ("teardown()", "on unmount", "Release everything. Asserted by the memory-leak gate.", "A plugin that leaks fails CI, not a customer's workstation."),
]

# Performance budgets — rows, mode, first paint, sort, filter keystroke, scroll, heap, notes
BUDGETS = [
 ("1,000",     "client",                   "≤ 120 ms", "≤ 40 ms",  "≤ 32 ms", "60 fps", "< 12 MB",  "Baseline. Anything slower is a defect, not a trade-off."),
 ("10,000",    "client, virtualised",      "≤ 180 ms", "≤ 120 ms", "≤ 50 ms", "60 fps", "< 45 MB",  "The largest set we allow fully client-side by default."),
 ("100,000",   "server ops, windowed",     "≤ 200 ms", "server",   "≤ 50 ms", "60 fps", "< 70 MB",  "Client mode refuses here and says why."),
 ("500,000",   "server ops, cursor",       "≤ 200 ms", "server",   "≤ 50 ms", "60 fps", "< 70 MB",  "Heap is flat above 100k by construction."),
 ("1,000,000+","server, or analytics plugin","≤ 200 ms","server",  "≤ 50 ms", "60 fps", "< 90 MB",  "<b>Client-side 1M is not offered.</b> TanStack v9 — the best engine measured — retains 380 MB for 1M×8."),
 ("100+ cols", "column virtualisation",    "≤ 200 ms", "≤ 120 ms", "≤ 50 ms", "60 fps", "+ 8 MB",   "Flowsheets and claims ledgers."),
 ("1k upd/s",  "streaming",                "n/a",      "n/a",      "n/a",     "60 fps", "flat",     "Coalesced on an animation frame; only the arrivals counter moves."),
]

BUDGET_RULES = [
 ("Every interaction budget is an INP budget.",
  "Good INP is ≤200 ms at the 75th percentile and it is the most commonly failed Core Web Vital — 43% of sites still miss it. Our numbers sit inside it so the grid is never the reason a page fails."),
 ("Budgets are measured CPU-throttled, on the CI machine.",
  "A budget measured on an M-series laptop has not been measured. The target device is a shared ward workstation: 4 GB, a decade-old CPU, an EHR and two payer portals already open."),
 ("Heap is a gate, not a note.",
  "The memory column is the one that decides whether client mode is offered at all, and it is the number that made 1M-row client-side a non-goal."),
 ("The refusal threshold is measured, not chosen.",
  "Past it, <code>mode=\"client\"</code> throws in development and degrades to server mode in production. A silent four-second sort is worse than a clear error."),
 ("Every budget has a named owner phase and a CI ratchet.",
  "A performance claim in prose has a half-life of about six weeks."),
]

# Discovered gaps — the things the previous brief missed entirely
DISCOVERED = [
 ("FHIR pagination breaks the coverage sentence", "critical",
  "FHIR servers return opaque <code>link.next</code> URLs and the specification is explicit that a client must not construct its own paging URLs. <code>Bundle.total</code> is optional; major servers return nothing or an estimate, and Azure's FHIR service supports only <code>next</code> — no <code>first</code>, <code>last</code> or <code>previous</code>.",
  "The brief's flagship sentence — <em>&ldquo;Showing 8 of 1,284&rdquo;</em> — is <b>unavailable against a large share of real FHIR servers</b>, and so is any page number or jump-to-page control. Coverage needs an honest unknown-total form and the pagination UI must degrade to next/previous only."),
 ("`_include` breaks row-to-entry correspondence", "high",
  "FHIR applies <code>_include</code> and <code>_revinclude</code> <em>after</em> paging, so a page of 20 patients may return 140 entries.",
  "Any adapter that maps <code>Bundle.entry.length</code> to a row count is wrong. The adapter must partition by resource type and report what it could not map — the obligation ADR 0011 already places on adapters."),
 ("CSV formula injection is an unhandled security defect", "critical",
  "A cell beginning <code>=</code>, <code>+</code>, <code>-</code>, <code>@</code>, tab or CR is executed as a formula by Excel, Sheets and LibreOffice. OWASP notes that prefixing quotes is not sufficient — Excel can strip escaping on save-and-reopen, re-activating the payload — and that full-width variants (＝, ＋) execute in some locales.",
  "A patient's preferred name is free text a patient can supply. Export is therefore a remote-code-execution path from a patient into a biller's workstation. <b>This is a defect in the design as written, not a missing feature.</b>"),
 ("Client-side 1M rows was never achievable", "critical",
  "TanStack Table v9 — the best-measured engine in the category — retains <b>380 MB</b> for one million rows by eight columns, down from 2.71 GB in v8.",
  "The brief's performance table listed a 1M+ client-side row. On a 4 GB shared workstation running an EHR, 380 MB for eight columns is the entire budget, and a clinical grid has forty. <b>The row should be removed and the refusal made explicit.</b>"),
 ("SSR and hydration were not addressed at all", "high",
  "A virtualised grid renders 15 of 100,000 rows, so server and client markup differ and hydration fails. The common answer is to mark the grid client-only.",
  "Next.js App Router is the default stack for new digital-health products. &ldquo;<code>ssr: false</code> and a shrug&rdquo; is not an architecture — the answer is a server-rendered, non-virtualised first page that hands off to the client virtualiser, and it has to be designed rather than discovered."),
 ("Telemetry and error reporting can leak PHI", "critical",
  "An exception thrown inside a cell renderer conventionally carries the value that caused it. Error-tracking services store it.",
  "The grid must guarantee by construction that error objects and telemetry carry column keys and row <em>indices</em>, never values. No competitor addresses this and no healthcare buyer will fail to ask about it."),
 ("No renderer safety contract", "high",
  "Every competitor allows a custom cell renderer to return arbitrary markup. A cell rendering a note excerpt renders attacker-influenced content.",
  "The cell contract should make raw HTML injection impossible by type rather than discouraged in prose."),
 ("Memory leaks are nobody's regression suite", "high",
  "Detached DOM nodes and un-removed listeners are the classic grid leak, and heap snapshots in CI with a growth threshold are a solved technique.",
  "A ward workstation keeps one browser session for a fortnight and mounts this grid hundreds of times a shift. <b>No grid in this category gates on it</b>, and the failure mode is a workstation that degrades over a shift — which gets blamed on the hospital's hardware."),
 ("Server-side sort can be silently ignored", "high",
  "FHIR <code>_sort</code> support is server-dependent and several servers ignore an unsupported key rather than erroring.",
  "The grid would show an unsorted list under a header claiming a sort. It must detect the discrepancy and say so — a sort claim is a clinical claim once the column is a risk score."),
 ("Column spanning was used in our own mockup and never specified", "medium",
  "The masking figure spans a Part 2 notice across three columns.",
  "Found by reading our own artefact. It is a reminder that the mockups encode requirements the prose did not capture."),
 ("The npm scope in the proposal is not the scope we own", "medium",
  "<code>@oxygenui-design/fhir</code> is published; <code>@oxygenui-design</code> is the proven scope. The proposal's example names use <code>@oxygenui/*</code>.",
  "A trivial fix now and an expensive one after the first release."),
 ("AI features are already table stakes", "high",
  "Syncfusion ships semantic filtering and anomaly detection today; MUI X v9 ships an AI assistant in Premium.",
  "The brief treated AI as a differentiator. It is not. <b>The differentiator is provenance and refusal</b> — being the only grid where an AI-derived value cannot be mistaken for a verified one, and where an uncompilable query runs nothing."),
]
