# -*- coding: utf-8 -*-
"""The feature-gap matrix.

Row shape:
  area, capability,
  ag, tan, mui, hot, syn      support in each competitor: 3 full · 2 partial · 1 none · 0 n/a
  ours                        our support today: "none" | "brief" | "partial"
  hc                          the healthcare requirement, or "" if generic
  pri                         P0 | P1 | P2 | future | never
  rec                         the recommendation
"""

# support codes
FULL, PART, NONE, NA = 3, 2, 1, 0

GAPS = [
 # ---------------------------------------------------------------- core architecture
 ("Core architecture", "Framework-agnostic core with no framework assumptions",
  FULL, FULL, NONE, PART, PART, "brief",
  "A behavioural-health vendor on Angular and a payer on React must share one clinical grid, or the clinical rules fork.",
  "P0", "Adopt. The brief assumed React. This is the single largest architectural change in this review."),
 ("Core architecture", "Own IoC / service container in core",
  FULL, NONE, NONE, PART, PART, "none",
  "",
  "never", "Reject. AG Grid's IoC container is why its core is 500 KB and why nobody can read it. Use plain modules and explicit wiring."),
 ("Core architecture", "Signal-based reactivity in core",
  NONE, FULL, NONE, NONE, NONE, "none",
  "",
  "P0", "Adopt. TanStack v9 moved to alien-signals and got 79% faster row processing and 86% less heap. TC39 Signals is Stage 1 with Angular, Vue, Solid, Preact and MobX behind it; a bespoke observer layer would be legacy inside three years."),
 ("Core architecture", "Columnar (struct-of-arrays) row storage",
  NONE, NONE, NONE, NONE, NONE, "none",
  "A vitals flowsheet is 20 analytes × 2,000 timepoints. Row-of-objects storage allocates 40,000 objects for a shape that is natively columnar.",
  "P1", "Adopt behind a flag. Nobody in this category does it and it is the precondition for the Arrow/DuckDB path below."),
 ("Core architecture", "Immutable state transitions / replayable actions",
  PART, FULL, PART, NONE, NONE, "brief",
  "A replayable action log is what makes a grid's behaviour reconstructable in an incident review.",
  "P0", "Keep. Already in the brief as a reducer; make the action log an exportable artefact."),

 # ---------------------------------------------------------------- rendering
 ("Rendering", "DOM virtualisation, rows",
  FULL, NONE, FULL, FULL, FULL, "brief", "", "P0", "Keep."),
 ("Rendering", "DOM virtualisation, columns",
  FULL, NONE, FULL, FULL, FULL, "brief",
  "Flowsheets and claims ledgers are 60–200 columns.",
  "P0", "Keep."),
 ("Rendering", "DOM node recycling rather than unmount/remount",
  FULL, NA, PART, FULL, FULL, "none",
  "",
  "P1", "Adopt. The brief specified windowing but not recycling; React reconciliation of 40 unmounting rows per frame is the actual scroll cost."),
 ("Rendering", "Canvas rendering path",
  NONE, NA, NONE, NONE, NONE, "none",
  "",
  "never", "Reject, explicitly and in writing. Glide Data Grid proves canvas scales to millions of rows with flat memory — and it puts every cell outside the accessibility tree. For a surface a clinician uses all day under WCAG 2.2 AA, that is disqualifying. Document the rejection so it is not revisited annually."),
 ("Rendering", "Web Components / custom elements as the render target",
  NONE, NA, NONE, NONE, PART, "none",
  "",
  "P2", "Partially adopt — for the vanilla adapter only. React 19 finally passes properties correctly to custom elements, but shadow DOM cuts the token cascade and breaks forced-colors inheritance, which is where our status system lives."),
 ("Rendering", "Dynamic row heights with scroll anchoring",
  FULL, NA, PART, PART, PART, "brief",
  "A chip row that wraps at 90% zoom is a different height. Clinical rows are not uniform.",
  "P0", "Keep. Named in the brief as the hardest problem; it still is."),
 ("Rendering", "`content-visibility` / CSS containment for off-screen work",
  NONE, NA, NONE, NONE, NONE, "none", "",
  "P2", "Investigate. Cheap, standards-based, and complementary to windowing for the expanded-row case."),

 # ---------------------------------------------------------------- state & data
 ("State & data", "Client-side row model",
  FULL, FULL, FULL, FULL, FULL, "brief", "", "P0", "Keep."),
 ("State & data", "Infinite / windowed row model",
  FULL, NONE, FULL, PART, FULL, "brief", "", "P0", "Keep."),
 ("State & data", "Server-side row model with server grouping and aggregation",
  FULL, NONE, FULL, NONE, FULL, "brief",
  "A payer cohort is 5M rows. Grouping by plan cannot happen in the browser.",
  "P0", "Adopt AG Grid's four-row-model framing explicitly — it is the clearest mental model in the category and our brief collapsed it into one `mode` prop."),
 ("State & data", "Viewport row model for live streams",
  FULL, NONE, NONE, NONE, PART, "none",
  "An ADT feed should push only the rows a given user is looking at.",
  "P2", "Defer. AG Grid's own docs warn it is over-implemented. Revisit only with a customer who has the server for it."),
 ("State & data", "Cursor pagination as the default, not an option",
  PART, NONE, PART, NONE, PART, "brief",
  "<b>FHIR forces it.</b> Servers return opaque `link.next` URLs and the spec says you must not construct your own.",
  "P0", "Strengthen. The brief offered offset OR cursor; against FHIR, offset is not available at all."),
 ("State & data", "Grid works when the total row count is unknown",
  PART, NA, PART, NONE, PART, "none",
  "`Bundle.total` is optional in FHIR and several major servers return nothing or an estimate.",
  "P0", "<b>New requirement, and it breaks a claim in the brief.</b> 'Showing 8 of 1,284' is unavailable against many FHIR servers. Coverage must have an honest unknown-total form."),
 ("State & data", "Request cancellation and out-of-order response guards",
  FULL, NA, FULL, PART, FULL, "brief", "", "P0", "Keep."),
 ("State & data", "Response cache with TTL and explicit invalidation",
  PART, NA, FULL, NONE, PART, "partial",
  "A cached row is a stale clinical fact. TTL must be short and stated.",
  "P1", "Adopt MUI's shape (`set`/`get`/`clear`, TTL, `skipCache`) — it is the best-designed cache contract in the category — and add a visible staleness stamp."),
 ("State & data", "Apache Arrow / DuckDB-WASM analytical path",
  NONE, NONE, NONE, NONE, NONE, "none",
  "Population health and quality measures are analytical queries over 100k–5M rows that today force a round trip per facet.",
  "P2", "Investigate seriously as an optional plugin. Arrow + DuckDB-WASM is 10–100× faster than querying plain JS objects and handles multi-GB in the browser. Nobody in this category ships it and it is the only credible client-side answer above 100k rows."),

 # ---------------------------------------------------------------- filtering / sorting
 ("Filtering", "Column filters with typed operators",
  FULL, FULL, FULL, FULL, FULL, "brief", "", "P0", "Keep."),
 ("Filtering", "Nested boolean filter tree (AND/OR/NOT) as one value",
  FULL, PART, PART, NONE, FULL, "brief",
  "", "P0", "Keep. Our one-AST rule is stronger than any competitor's; AG Grid's advanced filter is a string DSL that cannot round-trip."),
 ("Filtering", "Filter model serialises to and from a URL and a stored view",
  FULL, PART, FULL, NONE, FULL, "brief", "", "P0", "Keep."),
 ("Filtering", "The active predicate rendered in words and printed",
  NONE, NONE, NONE, NONE, NONE, "brief",
  "A filtered list looks complete. 'No results' is indistinguishable from 'no patients have this problem'.",
  "P0", "Keep — this is a genuine differentiator and no competitor has it."),
 ("Filtering", "Coded-concept filters with hierarchy expansion",
  NONE, NONE, NONE, NONE, NONE, "brief",
  "'Diabetes' must optionally include its SNOMED descendants, and the choice must be explicit.",
  "P1", "Keep, and move the terminology expansion itself out of the grid — see §What not to build."),
 ("Sorting", "Multi-column sort with visible precedence",
  FULL, FULL, FULL, PART, FULL, "brief", "", "P0", "Keep."),
 ("Sorting", "Sort provenance for derived and model columns",
  NONE, NONE, NONE, NONE, NONE, "brief",
  "Sorting a worklist by a risk score is triage. HTI-1 requires 31 source attributes for predictive DSI.",
  "P0", "Keep — the strongest single differentiator in the whole proposal."),
 ("Sorting", "Sort is reachable-to-none (a grid you can un-sort)",
  FULL, FULL, PART, PART, FULL, "brief", "", "P0", "Keep."),
 ("Sorting", "Server-side sort where the server may refuse a key",
  PART, NA, PART, NONE, PART, "none",
  "FHIR `_sort` support is server-dependent; some servers ignore unsupported keys silently.",
  "P0", "<b>New.</b> The grid must detect an ignored sort and say so, rather than showing an unsorted list under a sorted header."),

 # ---------------------------------------------------------------- shaping
 ("Grouping", "Row grouping with sticky group headers",
  FULL, FULL, FULL, NONE, FULL, "brief", "", "P1", "Keep."),
 ("Grouping", "Server-side grouping with lazy group expansion",
  FULL, NONE, FULL, NONE, FULL, "brief", "", "P1", "Keep."),
 ("Aggregation", "Column aggregation and group summaries",
  FULL, FULL, FULL, PART, FULL, "brief", "", "P1", "Keep."),
 ("Aggregation", "Refuses to aggregate across incompatible units",
  NONE, NONE, NONE, NONE, NONE, "brief",
  "mmol/L and mg/dL in one column is a real flowsheet state.",
  "P1", "Keep. Differentiator."),
 ("Pivoting", "Pivot mode",
  FULL, NONE, FULL, NONE, FULL, "none",
  "Quality measures by facility × measure × quarter is a pivot, and it is currently built as a separate report screen.",
  "P2", "Adopt later, server-side only. Client-side pivot at cohort scale is not achievable and pretending otherwise is how grids get slow."),
 ("Tree data", "Tree data with partial / lazy branches",
  FULL, FULL, FULL, NONE, FULL, "brief",
  "A care plan branch that has not loaded is not an empty branch.",
  "P1", "Keep."),
 ("Master/detail", "In-place detail rows",
  FULL, PART, FULL, NONE, FULL, "brief", "", "P1", "Keep."),

 # ---------------------------------------------------------------- columns & rows
 ("Columns", "Resize, reorder, hide, pin — all with keyboard paths",
  PART, NONE, PART, PART, PART, "brief",
  "WCAG 2.2 SC 2.5.7 makes a drag-only reorder a failure.",
  "P0", "Keep. <b>No competitor has a complete keyboard path for all four</b>; this is a cheap, checkable win."),
 ("Columns", "Column groups / header spanning",
  FULL, FULL, FULL, FULL, FULL, "brief", "", "P1", "Keep."),
 ("Columns", "Column definitions are serialisable data, not JSX",
  FULL, FULL, PART, FULL, FULL, "brief",
  "A saved view and a role preset must be storable server-side.",
  "P0", "Keep. MUI and antd both allow JSX column children and both therefore cannot round-trip a column set."),
 ("Columns", "Auto-sizing / fit-to-content",
  FULL, NONE, FULL, FULL, FULL, "none", "", "P1", "Adopt. Cheap and expected; the brief omitted it entirely."),
 ("Columns", "Column spanning within a row",
  FULL, NONE, FULL, FULL, FULL, "partial",
  "A masked Part 2 region spans three columns — the brief's own mockup does this and never specified it.",
  "P1", "<b>Adopt. Discovered from our own mockup.</b>"),
 ("Rows", "Row pinning (top/bottom)",
  FULL, NONE, FULL, PART, FULL, "none",
  "The patient you are working stays pinned while you filter around them.",
  "P1", "Adopt. Omitted from the brief."),
 ("Rows", "Row spanning",
  FULL, NONE, PART, PART, FULL, "none", "", "P2", "Defer."),
 ("Rows", "Row reordering (drag + keyboard)",
  FULL, NONE, FULL, FULL, FULL, "none",
  "Triage order in a work queue is sometimes manual.",
  "P2", "Adopt later, with the keyboard path from day one."),

 # ---------------------------------------------------------------- interaction
 ("Selection", "Row, range and cell selection",
  FULL, FULL, FULL, FULL, FULL, "brief", "", "P0", "Keep row; range is a plugin."),
 ("Selection", "Selection as predicate + include/exclude ids",
  PART, NONE, PART, NONE, PART, "brief",
  "A bulk clinical write must re-resolve what it is about to touch.",
  "P0", "Keep. Differentiator."),
 ("Editing", "Cell and row editing with a commit phase",
  FULL, PART, FULL, FULL, FULL, "brief", "", "P1", "Keep."),
 ("Editing", "Validation with per-row outcome reporting",
  PART, NONE, PART, PART, FULL, "brief",
  "Twelve writes, nine succeed, two fail, one refused by policy — all three must render.",
  "P1", "Keep."),
 ("Editing", "Conflict detection with no preselected resolution",
  NONE, NONE, NONE, NONE, NONE, "brief", "", "P1", "Keep. Differentiator."),
 ("Editing", "Undo / redo",
  FULL, NONE, FULL, FULL, FULL, "brief",
  "Never for a signed or transmitted write.",
  "P2", "Plugin. Keep the clinical restriction."),
 ("Clipboard", "Copy / paste / fill handle",
  FULL, NONE, FULL, FULL, FULL, "brief", "", "P2", "Plugin, off by default in clinical recipes."),
 ("Clipboard", "Copy preserves masking",
  NONE, NONE, NONE, NONE, NONE, "brief", "", "P0", "Keep. Differentiator."),
 ("Keyboard", "Full two-dimensional cell navigation",
  FULL, NONE, FULL, FULL, FULL, "brief", "", "P0", "Keep."),
 ("Keyboard", "Documented, remappable keymap",
  PART, NONE, PART, PART, PART, "none",
  "A clinician who used one EHR for nine years has muscle memory that is worth more than our defaults.",
  "P1", "<b>Adopt. Nobody does this well and it is a real differentiator for daily users.</b>"),

 # ---------------------------------------------------------------- output
 ("Export", "CSV / Excel export",
  FULL, NONE, FULL, FULL, FULL, "brief", "", "P1", "Plugin."),
 ("Export", "Formula-injection–safe CSV",
  NONE, NA, NONE, NONE, NONE, "none",
  "A patient's preferred name is free text. `=cmd|...` in a name field becomes code execution on the exporter's machine.",
  "P0", "<b>Adopt immediately. Discovered gap, and it is a security defect, not a feature.</b> OWASP's own note is that naive escaping fails once Excel re-saves the file."),
 ("Export", "Export carries the query and the coverage sentence",
  NONE, NA, NONE, NONE, NONE, "brief", "", "P1", "Keep. Differentiator."),
 ("Printing", "Print / PDF with repeating headers",
  PART, NONE, PART, PART, FULL, "brief",
  "A printed worklist is still the handover artefact on most wards.",
  "P1", "Keep — and it is a genuine gap in every competitor."),

 # ---------------------------------------------------------------- platform
 ("Persistence", "Serialisable view document with a precedence chain",
  PART, NONE, PART, NONE, PART, "brief", "", "P0", "Keep. Strongest architectural idea in the brief."),
 ("Extensibility", "Plugin registration with tree-shaking",
  FULL, FULL, PART, PART, PART, "brief", "", "P0", "Keep, and copy AG Grid v33's module registry shape — it is the best in the category."),
 ("Extensibility", "Custom cell renderers, editors and filters",
  FULL, FULL, FULL, FULL, FULL, "brief", "", "P0", "Keep."),
 ("Theming", "Design-token theming without a CSS-in-JS runtime",
  PART, NA, NONE, PART, PART, "brief",
  "", "P0", "Keep. MUI's dependency on its own styling engine is the single most-cited reason teams reject it."),
 ("Theming", "Light / dark / high-contrast parity, gated by contrast tests",
  PART, NA, PART, PART, PART, "brief", "", "P0", "Keep. Differentiator."),
 ("i18n", "Message catalogue and locale-aware formatting",
  FULL, NA, FULL, FULL, FULL, "brief",
  "Patient / client / member / consumer / resident is a setting, not a synonym.",
  "P1", "Keep, and reuse the shipped `TerminologyProvider`."),
 ("i18n", "RTL",
  FULL, NA, FULL, FULL, FULL, "brief", "", "P1", "Keep — logical properties throughout."),
 ("Responsive", "Card transformation below a breakpoint",
  NONE, NA, PART, NONE, PART, "brief", "", "P1", "Keep. Differentiator."),
 ("SSR", "Server rendering / hydration story",
  PART, FULL, PART, PART, PART, "none",
  "Next.js App Router is the default stack for new digital-health products.",
  "P0", "<b>Adopt. Omitted from the brief entirely.</b> A virtualised grid cannot hydrate a full row set; the answer is a documented server-rendered first page plus a client-only virtualiser, not `ssr: false` and a shrug."),
 ("Bundle", "Tree-shakeable ESM with per-feature entry points",
  FULL, FULL, PART, NONE, PART, "brief", "", "P0", "Keep."),
 ("Bundle", "Published, gated bundle-size budgets",
  NONE, NONE, NONE, NONE, NONE, "partial",
  "", "P1", "Adopt. `size-limit` already runs in OxygenUI; the number should be public and per-entry-point."),
 ("Security", "XSS-safe rendering contract for custom cells",
  PART, PART, PART, PART, PART, "none",
  "A cell that renders a note excerpt is rendering attacker-influenced content.",
  "P0", "<b>Adopt. Discovered gap.</b> No competitor documents a renderer safety contract; ours should forbid raw HTML injection by type."),
 ("Security", "Telemetry that provably cannot carry PHI",
  NONE, NA, NONE, NONE, NONE, "none",
  "An error report containing a row is a breach.",
  "P0", "<b>Adopt. Discovered gap.</b> Error objects must carry column keys and row *indices*, never values."),

 # ---------------------------------------------------------------- healthcare
 ("Healthcare", "Typed absence taxonomy per cell",
  NONE, NONE, NONE, NONE, NONE, "brief", "Seven reasons a cell is empty, seven next actions.", "P0", "Keep. Differentiator."),
 ("Healthcare", "Required coverage declaration",
  NONE, NONE, NONE, NONE, NONE, "brief", "", "P0", "Keep, with the unknown-total form added."),
 ("Healthcare", "Identity-safe row rendering and disambiguation",
  NONE, NONE, NONE, NONE, NONE, "brief", "", "P0", "Keep. Differentiator."),
 ("Healthcare", "Column/cell/row disclosure policy",
  NONE, NONE, NONE, NONE, NONE, "brief", "", "P0", "Keep. Differentiator."),
 ("Healthcare", "Position-stable live updates",
  PART, NONE, PART, NONE, PART, "brief", "", "P0", "Keep. Differentiator."),
 ("Healthcare", "FHIR resource adapters",
  NONE, NONE, NONE, NONE, NONE, "none",
  "Nine resource types cover most of the surface.",
  "P1", "Adopt as a separate package. Never in core."),
 ("Healthcare", "Clinical cell catalogue",
  NONE, NONE, NONE, NONE, NONE, "brief", "", "P0", "Keep — and host the OxygenUI components rather than rebuilding them."),
 ("Healthcare", "Terminology binding (ICD-10, CPT, SNOMED, LOINC, RxNorm)",
  NONE, NONE, NONE, NONE, NONE, "none",
  "A diagnosis chip needs a display term for a code the grid does not hold.",
  "P1", "Adopt the *binding*, reject the *data*. See §What not to build."),

 # ---------------------------------------------------------------- quality
 ("Testing", "Accessibility gate in CI",
  NONE, NONE, PART, NONE, PART, "brief", "", "P0", "Keep — already the OxygenUI standard."),
 ("Testing", "Performance regression gate in CI",
  NONE, NONE, NONE, NONE, NONE, "brief", "", "P0", "Keep."),
 ("Testing", "Memory-leak regression gate",
  NONE, NONE, NONE, NONE, NONE, "none",
  "A ward workstation runs one browser session for a fortnight and mounts this grid hundreds of times a shift.",
  "P1", "<b>Adopt. Discovered gap. No grid in this category tests it</b>, and the failure mode is a workstation that degrades over a shift."),
 ("Testing", "Screen-reader matrix as a release gate",
  NONE, NONE, NONE, NONE, NONE, "brief", "", "P1", "Keep."),
 ("Testing", "Cross-framework adapter parity tests",
  PART, PART, NA, PART, PART, "none",
  "", "P0", "<b>Adopt.</b> If four adapters exist, one accessibility-tree assertion must run against all four or they will diverge."),
 ("DX", "Strong TypeScript inference from column definitions to row type",
  PART, FULL, PART, NONE, PART, "brief",
  "", "P0", "Keep, and match TanStack — its inference is the best in the category and it is why developers like it."),
 ("DX", "Interactive playground with editable data and code output",
  FULL, PART, FULL, FULL, FULL, "none", "", "P1", "Adopt."),
 ("DX", "Migration codemods from a competitor",
  PART, NONE, PART, NONE, NONE, "none",
  "", "P1", "<b>Adopt. This is a go-to-market weapon, not a nicety</b> — a one-command migration from antd `Table` or MUI `DataGrid` removes the largest adoption barrier."),
 ("AI", "Natural-language filtering",
  PART, NONE, FULL, NONE, FULL, "brief",
  "", "P1", "Keep — but note it is <b>no longer a differentiator</b>. MUI Premium and Syncfusion both ship it."),
 ("AI", "Anomaly detection",
  NONE, NONE, PART, NONE, FULL, "brief", "", "P2", "Keep as a lens. Syncfusion already ships this."),
 ("AI", "Provenance and confidence on every AI-derived value",
  NONE, NONE, NONE, NONE, NONE, "brief", "", "P0", "Keep. <b>This is the AI differentiator — not the AI features themselves.</b>"),
]

AREAS = []
for g in GAPS:
    if g[0] not in AREAS:
        AREAS.append(g[0])

PRI_ORDER = {"P0": 0, "P1": 1, "P2": 2, "future": 3, "never": 4}
COMPETITORS = ["AG Grid", "TanStack", "MUI X", "Handsontable", "Syncfusion"]
SUPPORT_WORD = {3: "full", 2: "partial", 1: "none", 0: "n/a"}
OURS_WORD = {
  "none": ("Not considered", "The previous brief does not mention it."),
  "brief": ("Specified in the brief", "Designed, not built."),
  "partial": ("Partly specified", "Named but under-specified."),
}
