# -*- coding: utf-8 -*-
"""Roadmap, classification, risks, what-not-to-build, scorecard."""

# P0/P1/P2/future classification — item, class, why, wave
CLASSES = [
 # ---- P0: without these it is not a credible product
 ("Framework-agnostic core with signals", "P0", "Everything else is cheap to change later. This is not.", 1),
 ("Framework-free DOM renderer owning accessibility", "P0", "Write the keyboard model and the ARIA contract once, or write them four times and diverge.", 1),
 ("Column model, row models, sort, filter AST, selection", "P0", "The engine.", 1),
 ("role=grid, roving focus, 24-binding keymap", "P0", "Determines the DOM structure. Cannot be retrofitted.", 1),
 ("Required coverage, with an unknown-total form", "P0", "Type-system change; retrofitting a required prop is a breaking change.", 1),
 ("Typed absence taxonomy", "P0", "Same reason. It is the type system, not a feature.", 1),
 ("Formula-injection-safe export writer", "P0", "A security defect. It ships with the first export, or the first export is a vulnerability.", 2),
 ("PHI-safe telemetry and error contract", "P0", "Cheap now, structural later.", 1),
 ("Renderer safety contract (no raw HTML by type)", "P0", "Type-level. Cannot be added after an ecosystem of renderers exists.", 1),
 ("Cursor pagination and unknown totals as first class", "P0", "FHIR forces it; offset is not available.", 2),
 ("Serialisable GridView with a precedence chain", "P0", "Versioned from the first commit or it becomes a migration.", 2),
 ("React adapter", "P0", "The reference adapter.", 1),
 ("Bundle, accessibility and performance gates in CI", "P0", "Gates added later never catch the regression that mattered.", 1),
 # ---- P1
 ("Virtualisation with node recycling and scroll anchoring", "P1", "The hardest engineering problem; needs the engine settled first.", 2),
 ("Server-side row model with lazy groups", "P1", "", 3),
 ("Healthcare cell host contract and the cell catalogue", "P1", "", 3),
 ("Disclosure policy: columns, cells, rows, break-glass", "P1", "", 4),
 ("FHIR adapter package", "P1", "", 4),
 ("Grouping, tree data, aggregation with unit refusal", "P1", "", 3),
 ("Inspector, bulk review, saved views, editing", "P1", "", 4),
 ("Print sheet with repeating headers", "P1", "Genuine competitor gap.", 4),
 ("Angular adapter", "P1", "Proves the agnosticism claim. Until a second adapter exists, the claim is untested.", 4),
 ("Remappable keymap", "P1", "Differentiator for daily users; nobody does it well.", 5),
 ("Memory-leak regression gate", "P1", "", 3),
 ("Cross-adapter accessibility parity test", "P1", "The moment a second adapter exists.", 4),
 ("Migration codemods from antd Table and MUI DataGrid", "P1", "Go-to-market weapon.", 5),
 ("Playground with editable data and code output", "P1", "", 5),
 ("Column auto-sizing, row pinning, column spanning", "P1", "Table stakes the brief omitted.", 3),
 ("SSR contract and documented hydration boundary", "P1", "", 2),
 # ---- P2
 ("Vue adapter and custom element", "P2", "On evidence of demand, not on symmetry.", 6),
 ("Arrow / DuckDB-WASM analytics plugin", "P2", "The only credible client-side answer above 100k, and a large bet.", 6),
 ("AI plugin: NL filter, proposals, summaries, anomaly lens", "P2", "Optional by construction.", 6),
 ("Pivot, server-side only", "P2", "", 6),
 ("Range selection, clipboard, fill handle, undo", "P2", "Plugins, off by default in clinical recipes.", 5),
 ("Devtools panel", "P2", "Debuggability as a feature; no competitor has one.", 6),
 ("Row reordering, row spanning", "P2", "", 6),
 ("Transposed layout (flowsheet, MAR)", "P2", "Still provisional; decide on evidence at the end of wave 3.", 5),
 # ---- future / never
 ("Viewport row model", "future", "AG Grid's own docs warn it is over-implemented. Wait for a customer with the server for it.", 0),
 ("Canvas rendering", "never", "Takes every cell out of the accessibility tree. Disqualifying for an all-day clinical surface.", 0),
 ("Terminology data (ICD-10, SNOMED, LOINC content)", "never", "Licensed, versioned, jurisdictional clinical content. Bind to a service; never ship the data.", 0),
 ("A formula engine", "never", "HyperFormula is GPLv3 and a spreadsheet metaphor invites bulk paste into clinical fields.", 0),
 ("Charting inside the grid", "never", "A sparkline cell is a cell. A chart is a different component with a different accessibility model.", 0),
 ("Audit log storage", "never", "A client that records its own access is a client that can choose not to.", 0),
 ("An IoC container", "never", "The single clearest lesson from AG Grid's core.", 0),
 ("Real-time collaboration / CRDTs", "never", "A different product. Co-presence indicators are enough, and they already ship.", 0),
]

WAVES = {
 1: ("Wave 1 — the spine", "5–6 weeks",
     "A framework-agnostic engine, a framework-free renderer, a React adapter, and every gate that will ever guard them.",
     "One grid, one framework, no healthcare, but with the keyboard model, the ARIA contract, coverage, absence and the CI gates already in place. Nothing after this changes the consumer API."),
 2: ("Wave 2 — scale and truth", "4–5 weeks",
     "Virtualisation with recycling and anchoring, the server contract, cursor pagination, unknown totals, the SSR boundary, and the export writer.",
     "100,000 rows, server-sorted, announcing absolute positions, exporting safely, with budgets asserted CPU-throttled in CI."),
 3: ("Wave 3 — clinical shape", "4–5 weeks",
     "The cell host contract, the catalogue as cells, grouping, tree data, aggregation with unit refusal, arrivals, sort provenance, and the memory gate.",
     "The caseload and the results inbox built from recipes with no bespoke cell code."),
 4: ("Wave 4 — work, disclosure and the second adapter", "5–6 weeks",
     "Inspector, bulk review, saved views, editing, the disclosure policy, the FHIR package — and the Angular adapter, which is what actually tests the agnosticism claim.",
     "One policy object driving six behaviours; a Part 2 row correct in four roles; identical accessibility trees from two adapters."),
 5: ("Wave 5 — developer product", "4 weeks",
     "Docs site, playground, codemods, the remappable keymap, plugins for clipboard and undo, and the transposed decision.",
     "A developer can evaluate, migrate and ship without talking to us."),
 6: ("Wave 6 — bets", "4–6 weeks",
     "Vue and custom element, the analytics plugin, the AI plugin, pivot, devtools.",
     "Each of these is optional and each is separately cancellable. None of them is on the critical path."),
}

RISKS = [
 ("Framework agnosticism multiplies the maintenance surface", "critical",
  "Four adapters means four release matrices, four test suites, four documentation sets and four bug queues — for a team that is currently one person plus an agent.",
  "<b>Mitigate by putting the DOM renderer below the adapters.</b> If adapters are 4 KB of binding and contain no grid logic, the multiplier applies to a small surface. If any adapter grows a feature, the strategy has failed and should be abandoned rather than nursed. <b>Ship React only in wave 1; do not claim agnosticism until Angular exists.</b>"),
 ("A separate repository doubles the release and governance overhead", "high",
  "Two repos, two CI configurations, two changelogs, and a cross-repo dependency on <code>@oxygenui-design/tokens</code> that will drift.",
  "Accept it, but only with a rule: the grid may depend on OxygenUI L0 packages and nothing else. If it needs an L2 component, that component moves down to L0 or is inlined."),
 ("The grid becomes a second design system by accident", "high",
  "A grid that owns its own theming, its own icons and its own intl is a competing system with the library it came from.",
  "Forbid it structurally: <code>grid-dom</code> may reference tokens and may not define them. A contrast gate runs against the OxygenUI token surface, not a local one."),
 ("Scroll anchoring across dynamic row heights", "high",
  "The single hardest engineering problem here, and the one most likely to be subtly wrong for months. Glide abandoned DOM virtualisation over exactly this.",
  "Budget it explicitly in wave 2 with its own acceptance test, and specify node recycling from the start rather than discovering the need."),
 ("Signals in the core is a bet on a Stage 1 proposal", "medium",
  "TC39 Signals is Stage 1. It may change or stall.",
  "That is why <code>grid-signals</code> is a separate package and a façade. The core imports our interface, never a vendor's. If TC39 lands, one package changes; if it stalls, nothing does."),
 ("Being mistaken for a compliance boundary", "critical",
  "A grid with masking, break-glass and disclosure events looks like it enforces minimum necessary. It does not and cannot.",
  "Write the <code>limitations</code> copy before the code, and put the boundary in the README at the same prominence as the capability. This is the one risk that can damage the company rather than the product."),
 ("No clinician reviewer", "critical",
  "Every clinical rule in this and the previous document is derived from literature. This is now the fourth artefact blocked on it.",
  "Name one and budget for it before wave 3. Until then, label the clinical layer as a well-researched proposal — which is what the report footer does."),
 ("Open-source expectations without an open-source plan", "high",
  "A public repository invites issues, PRs, security reports and support expectations. AG Grid, MUI and Handsontable all run funded teams behind their open cores.",
  "Decide the licence and the support posture <em>before</em> the repository is public. My recommendation is MIT for core, renderer, adapters and healthcare; a separate commercial licence only for the enterprise recipes pack; and an explicit, published statement that issues are triaged weekly and support is not guaranteed."),
 ("The behavioural-health weighting is still an unvalidated bet", "high",
  "Four of the fourteen recipes assume a behavioural-health buyer.",
  "Unchanged from the previous brief, and still unsettled."),
 ("Two adapters will diverge on accessibility without a shared test", "high",
  "It is the predictable failure of every multi-framework component library.",
  "One accessibility-tree assertion, run against every adapter, from the day the second adapter exists. This is the same construction <code>e2e/bridge-hosts.spec.ts</code> already uses in OxygenUI."),
]

NOT_BUILDING = [
 ("Canvas rendering", "It scales beautifully and removes every cell from the accessibility tree. For an all-day clinical surface under WCAG 2.2 AA that is disqualifying. Written down so it is not re-proposed annually."),
 ("An IoC container or a bespoke internal framework", "AG Grid's is the clearest cautionary tale in the category: large core, unreadable stack traces, no outside contribution."),
 ("A formula engine or spreadsheet mode in core", "HyperFormula is GPLv3 unless licensed, and the metaphor invites bulk paste into fields with clinical consequence. If a customer genuinely needs it, they should use Handsontable for that screen."),
 ("Terminology content", "ICD-10, CPT, SNOMED, LOINC and RxNorm are licensed, versioned, jurisdictional clinical data. We bind to a terminology service and render what it returns. Shipping the data would make us a content vendor with a legal surface we cannot support."),
 ("Charts inside the grid", "A sparkline is a cell. A chart is a different component with a different accessibility model and a different data shape. AG Grid's integrated charts are why AG Charts exists as a separate product."),
 ("Audit log storage or retention", "A client that records its own access is a client that can choose not to. We emit; the server records."),
 ("Real-time collaborative editing", "A different product with a different consistency model. Co-presence indicators already ship in <code>CareTeamPresence</code> and are sufficient."),
 ("A viewport row model", "AG Grid's own documentation warns that people implement it when they should not. Wait for a customer whose server can actually push per-viewport."),
 ("Our own virtualisation for the docs site", "Use the grid. If it is not good enough for our own documentation, it is not good enough."),
 ("A second search surface", "<code>ChartCommandPalette</code> ships. Compose it."),
 ("Framework agnosticism beyond four adapters", "Svelte, Qwik and Solid are served by the custom element. A per-framework package for each is how a two-person team drowns."),
 ("An enterprise licence key checker", "Runtime licence enforcement is user-hostile and trivially removable. Gate on the registry, not in the bundle."),
]

# Scorecard — dimension, current (brief), proposed, weight, note
SCORE = [
 ("Architectural correctness",  4, 9, 3, "React-only and single-package becomes framework-agnostic with a small stable core."),
 ("Performance ceiling",        5, 8, 3, "The 1M client-side claim was wrong; the honest ceiling is higher-value than the fictional one."),
 ("Accessibility",              8, 9, 3, "Already the strongest part; the DOM renderer makes it survive four frameworks."),
 ("Healthcare differentiation", 9, 9, 3, "Unchanged and still the reason to build this."),
 ("Security posture",           3, 8, 2, "Export injection, telemetry leakage and renderer safety were all unaddressed."),
 ("Interoperability realism",   3, 8, 2, "FHIR pagination and totals invalidate a flagship claim; fixing it makes the product real."),
 ("Developer experience",       6, 9, 2, "Types, playground, codemods, devtools."),
 ("Maintainability at 5 years", 5, 7, 3, "Framework agnosticism is a cost. A small core and thin adapters is the only version that survives."),
 ("Documentation",              6, 9, 2, "From a research brief to a product."),
 ("Commercial readiness",       3, 7, 1, "Licence, scope, support posture and migration path all still to decide."),
]
