# -*- coding: utf-8 -*-
"""Sections 22–32."""
from model import fill
from mocklib import ic
import d_plan, d_arch, d_gap, figs, figs2


def s_readme():
    return fill("""
<div class="prose">
<p class="lede2">The README has one job: in fifteen seconds, convince an engineer who is currently evaluating
AG&nbsp;Grid that this is a serious piece of engineering. Everything below is in service of that.</p>

<h4>The eight decisions in this draft</h4>
<ol class="claims">
<li><b>The tagline is a claim, not a category.</b> &ldquo;The data grid that knows a row is a person&rdquo; says
what is different. &ldquo;A high-performance enterprise data grid&rdquo; says what everyone says.</li>
<li><b>&ldquo;Why this exists&rdquo; comes before the feature list.</b> A feature list invites comparison on
features, which is the axis we lose on for two years. The failure mode we prevent is the axis we win on.</li>
<li><b>The limitation appears above the fold.</b> A healthcare library that buries its compliance boundary reads
as either naïve or evasive. Putting it beside the capability is what makes the capability believable.</li>
<li><b>Four framework tabs in the quick start</b> — and, until Angular ships, <b>only React is shown</b>. Listing
four and supporting one is the fastest way to lose the audience.</li>
<li><b>A real animated capture</b>, not a static screenshot: 100,000 rows, keyboard-only, both themes. The claims
that matter here are motion claims.</li>
<li><b>Badges that are true and checkable</b>, generated by CI: core size, coverage, WCAG level, framework count.
No &ldquo;blazing fast&rdquo;.</li>
<li><b>The migration command is in the README</b>, not buried in docs. It is the largest adoption barrier and one
line removes it.</li>
<li><b>Support posture is stated honestly.</b> &ldquo;Issues triaged weekly; support is not guaranteed and is not
a contract&rdquo; is better than silence, and far better than an implied SLA we cannot honour.</li>
</ol>
</div>

@@FIG@@

<div class="prose"><div class="note">
<p><b>What is deliberately absent.</b> No sponsor wall, no star-count plea, no comparison table naming
competitors — a comparison table in a README reads as insecurity, and it dates badly. The comparison lives in the
documentation where it can be maintained and where the honest &ldquo;AG&nbsp;Grid is better at this&rdquo; rows can
appear without looking like a concession.</p>
</div></div>
""", FIG=figs2.fig_readme())


def s_play():
    return fill("""
<div class="prose">
<p class="lede2">A playground is not a demo. A demo shows the grid working; a playground lets a sceptical engineer
try to break it. Four controls do almost all of the work, and each corresponds to a claim in this document that
would otherwise have to be taken on trust.</p>

<div class="tblwrap"><table class="dtbl">
<thead><tr><th style="width:20%">Control</th><th style="width:34%">Proves</th><th>Why it must be interactive</th></tr></thead>
<tbody>
<tr><td><b>Row count</b> 100 → 1M</td><td>The performance claim, and the refusal.</td><td>Turning it to 1M and getting an explicit, explained refusal is more convincing than any benchmark table — it shows we know where the wall is.</td></tr>
<tr><td><b>Recipe</b></td><td>The configuration claim.</td><td>Switching roster → caseload → MAR without changing code is the whole &ldquo;recipes are data&rdquo; argument, made in one click.</td></tr>
<tr><td><b>Framework</b></td><td>The agnosticism claim.</td><td>The generated code changes and the rendered grid does not. Until Angular ships, this control shows one tab — honestly.</td></tr>
<tr><td><b>Policy</b></td><td>The disclosure claim.</td><td>Switching from clinician to &ldquo;no treatment relationship&rdquo; and watching columns disappear and rows mask is the demonstration that sells to a security reviewer.</td></tr>
</tbody></table></div>
</div>

@@FIG@@

<div class="prose">
<h4>Four things it must do that most playgrounds do not</h4>
<ul>
<li><b>Ship the real 100k fixture.</b> A playground with eight rows teaches nothing about a grid.</li>
<li><b>Show live frame timings and heap</b> in the corner. If we claim budgets, let people watch them.</li>
<li><b>Have a keyboard mode</b> that hides the pointer and shows the active binding as you press it — the fastest
way to demonstrate the accessibility work, and it demos well.</li>
<li><b>Copy code that actually runs</b>, including the imports and the plugin registrations implied by the toggles.</li>
</ul>
<div class="note">
<p><b>And one thing it must not be.</b> Not an embedded code sandbox. A sandbox cannot resolve our registry, our
tokens or our fixtures, so it opens broken — the same conclusion the Component Library Standard already reached
for OxygenUI. Editable configuration with generated code is more useful and always works.</p>
</div>
</div>
""", FIG=figs2.fig_playground())


def s_cicd():
    gates = [
      ("Type check + lint", "every PR", "Strict TypeScript across all packages via project references.", "yes"),
      ("Unit + property", "every PR", "Engine suites; property tests at 40,000 rows.", "yes"),
      ("Renderer + keyboard", "every PR", "Real browser, three engines.", "yes"),
      ("Accessibility", "every PR", "axe per story × themes × densities. <b>Zero violations, not a budget.</b>", "yes"),
      ("Cross-adapter parity", "every PR, once 2 adapters exist", "One accessibility-tree assertion per adapter.", "yes"),
      ("Bundle size", "every PR", "<code>size-limit</code> per entry point, ratcheted. <b>Published in the README.</b>", "yes"),
      ("Performance", "every PR", "CPU-throttled budgets at 1k/10k/100k, ratcheted.", "yes"),
      ("Memory", "nightly", "200 mount/unmount cycles, heap growth threshold.", "no — too slow for PRs"),
      ("Visual regression", "every PR", "3 engines × themes × densities × recipes.", "yes"),
      ("Security", "every PR", "Export payload bytes, telemetry payload, clipboard mask.", "yes"),
      ("SSR", "every PR", "One hydration test per adapter.", "yes"),
      ("Screen readers", "pre-release, manual", "NVDA/JAWS/VoiceOver × 3 engines.", "no — cannot be automated"),
      ("Supply chain", "every PR", "Blocking audit, SBOM, provenance, SHA-pinned actions.", "yes"),
    ]
    trs = "".join('<tr><td class="nw"><b>%s</b></td><td class="nw t3">%s</td><td>%s</td><td class="nw t3">%s</td></tr>' % g
                  for g in gates)
    return fill("""
<div class="prose">
<p class="lede2">You asked for justification rather than fashion, so every choice below is either &ldquo;already
in use and working&rdquo; or has a named reason.</p>

<div class="tblwrap"><table class="dtbl">
<thead><tr><th style="width:22%">Tool</th><th class="nw">Verdict</th><th>Reason</th></tr></thead>
<tbody>
<tr><td><b>pnpm workspaces</b></td><td><span class="dec-v adopt">adopt</span></td><td>Already in use. Strict linking catches phantom dependencies, which matters when the central claim is that core has none.</td></tr>
<tr><td><b>Turborepo</b></td><td><span class="dec-v adopt">adopt</span></td><td>Already in use. Remote caching matters once the benchmark suite is on the critical path.</td></tr>
<tr><td><b>TypeScript project references</b></td><td><span class="dec-v adopt">adopt</span></td><td>Fifteen packages without them means a full rebuild per change.</td></tr>
<tr><td><b>Changesets</b></td><td><span class="dec-v adopt">adopt</span></td><td>Already in use. Independent per-package versioning is exactly the problem it solves.</td></tr>
<tr><td><b>ESM only</b></td><td><span class="dec-v adopt">adopt</span></td><td>Correct 2026 default. Dual-publishing CJS is a permanent tax; add it only when a named customer asks.</td></tr>
<tr><td><b>Conventional commits</b></td><td><span class="dec-v adopt">adopt</span></td><td>Already enforced by commitlint in OxygenUI; the changelog quality is worth the friction.</td></tr>
<tr><td><b>Nx</b></td><td><span class="dec-v reject">reject</span></td><td>Turborepo already does what we need. Nx's generators and plugin ecosystem would be unused ceremony.</td></tr>
<tr><td><b>Runtime licence key</b></td><td><span class="dec-v reject">reject</span></td><td>User-hostile, trivially removable, and it puts a console warning in a clinician's browser. Gate on the registry, not in the bundle.</td></tr>
<tr><td><b>Canary / nightly builds</b></td><td><span class="dec-v partial">later</span></td><td>Useful once there is more than one consumer. Before that it is ceremony.</td></tr>
</tbody></table></div>

<h4>The gates</h4>
<p>A gate added later never catches the regression that mattered. All of these should exist in wave one, when
they are cheap and there is nothing to break.</p>
</div>

<div class="tblwrap"><table class="dtbl">
<thead><tr><th style="width:20%">Gate</th><th class="nw">When</th><th>What</th><th class="nw">Blocking</th></tr></thead>
<tbody>@@TRS@@</tbody></table></div>

<div class="prose">
<h4>Versioning and support, stated before the first release</h4>
<ul>
<li><b>Semver, with a published deprecation policy</b> — deprecate in a minor with a codemod where possible,
remove in the next major, and never remove without a documented migration.</li>
<li><b>The <code>GridView</code> document is versioned independently</b> and from the first commit, because it
lives in a customer's database and a schema change there is a migration you do not control.</li>
<li><b>An <code>experimental</code> tier</b> matching OxygenUI's stability tiers, so the AI and analytics plugins
can ship without freezing their APIs.</li>
<li><b>Support posture in writing.</b> Issues triaged weekly, security reports privately, no SLA implied. Silence
here reads as an implied contract.</li>
</ul>
<div class="note">
<p><b>The licence question needs answering before the repository is public, not after.</b> My recommendation: MIT
for core, signals, DOM, adapters, healthcare, FHIR, export, filters and testing — everything that a security
reviewer needs to read and everything an ecosystem needs to trust. A separate commercial licence <em>only</em> for
an enterprise recipe pack, with the licence named in every file. Note the trap in §@@N:notbuild@@: HyperFormula
is GPLv3 unless licensed, so vendoring a formula engine would make our position radioactive for exactly the
buyers we want.</p>
</div>
</div>
""", TRS=trs)


def s_ai():
    return """
<div class="prose">
<p class="lede2">The brief treated AI as a differentiator. That is no longer true and the section needs
re-scoping around what is.</p>

<div class="a-alert warning" style="font-size:.88rem;margin-bottom:1rem">@@IC@@<span>
<b>Syncfusion ships semantic filtering and anomaly detection in its data grid today. MUI X v9 ships an AI
assistant in Premium.</b> Natural-language filtering is table stakes, not an edge. Anything we build here will be
matched within two releases.</span></div>

<h4>What is actually defensible</h4>

<p><b>Provenance, refusal and confirmation.</b> Every competitor's AI feature produces an answer. Ours should be
the only one that can produce <em>no answer, visibly</em>, and the only one where an AI-derived value cannot be
mistaken for a verified one at a glance. That is not a model capability — it is a type system and a rendering
contract, and it is very hard to retrofit into a product that shipped without it.</p>

<ol class="claims">
<li><b>AI output is a provenance state of a value, not a kind of column.</b> The catalogue already has the
states: <code>ClinicalStatus</code> has <em>AI draft</em>, <code>ResultValue</code> has <em>AI extracted</em>,
<code>ProvenanceChip</code> has the whole chain. Nothing new is needed to render AI honestly, and anything that
invents a new treatment is creating a second vocabulary for the same idea.</li>
<li><b>Never mix generated and verified values in one cell.</b> A row may mix; a cell may not, because a reader
reads a cell as one fact.</li>
<li><b>Distinguishable without colour.</b> A glyph and a word. A purple tint disappears in forced-colors mode,
which is precisely where it must not.</li>
<li><b>The proposal channel never writes.</b> AI may propose a filter, a column, a grouping or an action.
Applying it is a human act, and the applied artefact is always the same kind of object a human could have made by
hand — which is what makes it reviewable and reversible.</li>
<li><b>An uncompilable query runs nothing.</b> No approximation, ever. <b>A silently narrowed cohort looks
exactly like a correct answer</b>, and in a clinical list that is the most dangerous single failure available.</li>
</ol>

<h4>PHI and the model boundary</h4>
<ul>
<li><b>Natural-language filtering needs the schema, not the data.</b> Column keys, types and enum values compile
a query. <b>No row ever leaves the browser for a filter.</b> This is both a privacy property and an architectural
one, and it should be stated in the plugin's own documentation.</li>
<li><b>Row summarisation does need the row</b>, so it is a different risk class and a different consent
conversation. It must be separately switchable, and the application must supply the endpoint — we never choose a
provider on a customer's behalf.</li>
<li><b>Anomaly detection runs locally</b> where it can: an outlier against the visible cohort is arithmetic, not
inference, and calling it AI when it is a z-score would be dishonest labelling.</li>
</ul>

<h4>Hallucination, concretely</h4>
<p>The risk is not a wrong sentence in a summary. It is a <b>plausible filter</b>. &ldquo;High-risk patients who
missed appointments this month&rdquo; has at least four ambiguities — which risk model, which threshold, what
counts as missed, whose month — and a system that resolves them silently produces a defensible-looking cohort
that is wrong in a way nobody can see. Hence: compile to chips, show the chips, and require the human to press
run. The previous brief got this right and it remains the strongest AI idea in either document.</p>

<div class="note">
<p><b>And the structural rule.</b> <code>grid-ai</code> is a plugin in its own package with its own dependency on
<code>copilot-core</code>. Core has no AI code, no AI types and no AI-shaped extension points. A clinical list
must be able to exist with no model anywhere near it.</p>
</div>
</div>
""".replace("@@IC@@", ic("alert", "i ic"))


def s_risks():
    trs = "".join(
      '<div class="eng"><div class="eng-h"><span class="sev %s">%s</span><b>%s</b></div>'
      '<div class="eng-b"><div class="blk"><span class="k">The risk</span><p>%s</p></div>'
      '<div class="blk"><span class="k">Mitigation</span><p>%s</p></div></div></div>' % (s, s, t, w, m)
      for t, s, w, m in d_plan.RISKS)
    return fill("""
<div class="prose">
<p class="lede2">Ten risks. Two are marked critical, and only one of those is technical.</p>
</div>

@@TRS@@

<div class="prose">
<h4>Technical debt we would be taking on deliberately</h4>
<div class="tblwrap"><table class="dtbl">
<thead><tr><th style="width:26%">Debt</th><th>Why we would take it</th></tr></thead>
<tbody>
<tr><td><b>A signals façade over a third-party implementation</b></td><td>TC39 Signals is Stage 1. The façade is one file and it is the cheapest possible hedge — but it is an abstraction over an abstraction, and if TC39 stalls we will still be carrying it in 2030.</td></tr>
<tr><td><b>A DOM renderer that is not React</b></td><td>Every React developer who reads our source will find it unfamiliar. That is the price of writing accessibility once, and it will slow outside contribution.</td></tr>
<tr><td><b>Two repositories sharing a token package</b></td><td>They will drift. The contrast gate running against the OxygenUI token surface is the only thing that will catch it.</td></tr>
<tr><td><b>Recipes as data</b></td><td>Powerful, and it means a recipe's schema is a public API that lives in customers' databases. Version it from commit one.</td></tr>
<tr><td><b>The <code>experimental</code> tier</b></td><td>Useful, and it will be abused as a place to leave things forever unless leaving it is a dated commitment.</td></tr>
</tbody></table></div>
<div class="note">
<p><b>The risk I would watch most closely is not on the list above.</b> It is scope. This document describes
26–32 weeks of work for a team that has been shipping one component per session. The single most important
discipline is that <b>wave one is shippable alone</b> and every wave after it is separately cancellable — so that
stopping is always a decision rather than a failure.</p>
</div>
</div>
""", TRS=trs)


def s_notbuild():
    trs = "".join(
      '<tr><td class="nw"><b>%s</b></td><td>%s</td></tr>' % n for n in d_plan.NOT_BUILDING)
    return fill("""
<div class="prose">
<p class="lede2">You asked me to tell you what should not be implemented and what belongs outside the grid. This
is the section I would keep in the repository, because most of these will be proposed again — some of them
annually.</p>
</div>

<div class="tblwrap"><table class="dtbl">
<thead><tr><th style="width:26%">Not building</th><th>Why</th></tr></thead>
<tbody>@@TRS@@</tbody></table></div>

<div class="prose"><div class="note">
<p><b>The three worth arguing hardest.</b> <b>Canvas</b>, because it is genuinely faster and the argument against
it is a value judgement about who the software is for. <b>Terminology data</b>, because a customer will ask and
it will feel like a small favour right up until the first licence audit. And <b>an audit log</b>, because it
looks like a feature and it is actually a liability: a client that records its own access is a client that can
choose not to, and shipping one implies a guarantee we cannot keep.</p>
</div></div>
""", TRS=trs)


def s_migration():
    return """
<div class="prose">
<p class="lede2">There is no code to migrate — §@@N:audit@@. So this section covers the two migrations that do
exist: <b>the design</b>, and <b>consumers coming from another grid</b>, which is the one that will matter
commercially.</p>

<h4>1 · Migrating the design</h4>
<div class="tblwrap"><table class="dtbl">
<thead><tr><th style="width:22%">From the brief</th><th class="nw">Action</th><th>Note</th></tr></thead>
<tbody>
<tr><td>The clinical thesis, coverage, absence, identity safety, disclosure, sort provenance, position-stable updates, the cell host contract, the fourteen recipes</td><td><span class="dec-v adopt">carry over</span></td><td>Unchanged. This is the product.</td></tr>
<tr><td><code>Coverage.total: number</code></td><td><span class="dec-v partial">amend</span></td><td>→ <code>number | "unknown"</code>. Non-negotiable given FHIR.</td></tr>
<tr><td>Seven absence reasons</td><td><span class="dec-v partial">amend</span></td><td>→ eight; add <code>source-unreachable</code>.</td></tr>
<tr><td>Seven cell obligations</td><td><span class="dec-v partial">amend</span></td><td>→ eight; add mask state, which is what makes safe export possible.</td></tr>
<tr><td>Offset <em>or</em> cursor pagination</td><td><span class="dec-v partial">amend</span></td><td>Cursor is the default; offset is the special case.</td></tr>
<tr><td>1M rows client-side</td><td><span class="dec-v reject">delete</span></td><td>Replace with an explicit, explained refusal.</td></tr>
<tr><td>One React package, antd-compatible</td><td><span class="dec-v reject">replace</span></td><td>Five layers, fifteen packages. antd parity survives as an adapter-level compatibility surface.</td></tr>
<tr><td>&ldquo;AI is a differentiator&rdquo;</td><td><span class="dec-v reject">replace</span></td><td>Provenance and refusal are the differentiators.</td></tr>
<tr><td>The 23 prototypes</td><td><span class="dec-v adopt">reuse</span></td><td>They become the playground's recipe presets and the visual-regression corpus. <b>They also encoded requirements the prose missed</b> — column spanning was found by reading one.</td></tr>
</tbody></table></div>

<h4>2 · Migrating consumers — the commercially important one</h4>

<p>The largest barrier to adopting a new grid is not features; it is the fortnight of work to move. One command
removes it, and it is a go-to-market weapon rather than a nicety.</p>

<pre class="code"><code>npx @oxygenui-design/grid-codemod from-antd     <span class="c-c">// columns, dataSource, rowSelection, onChange</span>
npx @oxygenui-design/grid-codemod from-mui      <span class="c-c">// GridColDef → GridColumn, DataSource → GridDataSource</span>
npx @oxygenui-design/grid-codemod from-aggrid   <span class="c-c">// ColDef → GridColumn; reports what needs a human</span></code></pre>

<div class="tblwrap"><table class="dtbl tight">
<thead><tr><th style="width:20%">From</th><th style="width:34%">Mechanical</th><th>Needs a human, and the codemod says so</th></tr></thead>
<tbody>
<tr><td><b>antd <code>Table</code></b></td><td><code>columns</code>, <code>dataSource</code>, <code>rowKey</code>, <code>rowSelection</code>, <code>pagination</code>, <code>onChange</code>, <code>expandable</code>, <code>scroll</code>, <code>sticky</code>.</td><td><code>coverage</code> — required, and no default is honest. <code>&lt;Table.Column&gt;</code> children, which cannot be serialised and must become objects.</td></tr>
<tr><td><b>MUI X</b></td><td><code>GridColDef</code> → <code>GridColumn</code>; <code>getRows</code> maps almost exactly onto ours.</td><td><code>renderCell</code> returning arbitrary JSX; <code>sx</code> styling; anything relying on the MUI theme.</td></tr>
<tr><td><b>AG&nbsp;Grid</b></td><td><code>ColDef</code> → <code>GridColumn</code>; row-model choice maps to our modes.</td><td>The imperative <code>GridApi</code> surface — the hardest of the three, and where the codemod should emit a report rather than guess.</td></tr>
</tbody></table></div>

<div class="note">
<p><b>The rule for every codemod:</b> it must be <em>lossy-loudly</em>. Where it cannot translate, it leaves the
original code, inserts a comment naming the reason, and prints a summary. A codemod that silently produces
plausible-but-wrong output is worse than no codemod — which is the same principle as the natural-language filter,
one layer down.</p>
</div>
</div>
"""


def s_roadmap():
    cards = []
    for n, (name, weeks, what, accept) in d_plan.WAVES.items():
        items = [c for c in d_plan.CLASSES if c[3] == n]
        chips = "".join('<span class="tg">%s</span>' % c[0] for c in items)
        cards.append(
          '<div class="rmphase"><div class="eng-h"><span class="num">%d</span><b>%s</b>'
          '<span class="st">%s</span><span style="flex:1 1 auto"></span></div>'
          '<div class="eng-b"><p style="margin:0 0 .55rem">%s</p>'
          '<div class="blk"><span class="k">Lands</span><div class="tagrow">%s</div></div>'
          '<div class="a-alert" style="margin-top:.7rem;font-size:12.5px">%s'
          '<span><b>Done means:</b> %s</span></div></div></div>' % (
            n, name, weeks, what, chips, ic("check", "i ic"), accept))
    return fill("""
<div class="prose">
<p class="lede2">Six waves, 26–32 weeks. Four changes from the brief's phasing, each with a reason.</p>
<ul>
<li><b>Accessibility and the type system are wave one</b>, not hardening. They determine the DOM structure and the
public types; a grid that adds <code>role="grid"</code> in month five rewrites its focus management in month
five.</li>
<li><b>The second adapter is wave four, not last.</b> It is the test of the entire agnosticism strategy, and
finding out it does not work in month eight is much cheaper than finding out in month fourteen.</li>
<li><b>The security fixes are wave one and two</b>, because the export writer ships in wave two and it must ship
safe.</li>
<li><b>Everything speculative is wave six</b> and separately cancellable: Vue, analytics, AI, pivot, devtools.
None is on the critical path.</li>
</ul>
</div>

<div class="rmphases">@@CARDS@@</div>

<div class="prose"><div class="note">
<p><b>Wave one is shippable alone</b>, and that is the point of the ordering. Five to six weeks produces a
framework-agnostic engine, a framework-free accessible renderer, a React adapter, coverage, absence, and every
gate that will ever guard them. A team could build a patient directory on it while wave two is being written, and
nothing after wave one changes the consumer API.</p>
</div></div>
""", CARDS="".join(cards))


def s_classes():
    return fill("""
<div class="prose">
<p class="lede2">Forty-five items. The classification rule is not importance — it is <b>cost of delay</b>. A P0 is
something that is cheap now and expensive or impossible later; a P2 is something that costs the same whenever it
is done.</p>
</div>

@@FIG@@
""", FIG=figs.fig_classes())


def s_diagram():
    return """
<div class="prose">
<p class="lede2">Everything in one picture. Read it top to bottom as dependency direction: each layer may import
from below, never from above.</p>
</div>

<pre class="tree">                          <b>APPLICATION</b>
        your EHR · your payer portal · your BH platform
                               │
   ┌───────────────────────────┼───────────────────────────┐
   │                    <b>L4 · PLUGINS</b>                       │   <i>opt-in, 0 bytes if unused</i>
   │  <em>export</em>  <em>filters</em>  <em>clipboard</em>  <em>undo</em>  <em>analytics</em>  <em>ai</em>   │
   └───────────────────────────┼───────────────────────────┘
                               │
   ┌───────────────────────────┼───────────────────────────┐
   │                   <b>L3 · ADAPTERS</b>                       │   <i>~4 KB each · binding only</i>
   │    <em>react</em>       <em>angular</em>       <em>vue</em>       <em>element</em>       │   <i>NO grid logic</i>
   └───────────────────────────┼───────────────────────────┘
                               │
   ┌───────────────────────────┴───────────────────────────┐
   │            <b>L2 · RENDER + DOMAIN</b>                        │
   │  <em>grid-dom</em>            <i>DOM · ARIA · focus · recycling</i>   │
   │  <em>grid-healthcare</em>     <i>coverage · absence · policy</i>      │
   │  <em>grid-fhir</em>           <i>Bundle source · resources</i>        │
   └───────────────────────────┼───────────────────────────┘
                               │
   ┌───────────────────────────┴───────────────────────────┐
   │                   <b>L1 · ENGINE</b>                          │
   │  <em>grid-core</em>       <i>row models · filter AST · view · geometry</i>│
   │  <em>grid-signals</em>    <i>reactivity façade → TC39 Signals</i>     │
   │                  <i>no DOM · no framework · no clinical terms</i>  │
   └───────────────────────────┼───────────────────────────┘
                               │
   ┌───────────────────────────┴───────────────────────────┐
   │              <b>L0 · FOUNDATION</b>  <i>(OxygenUI, reused)</i>       │
   │  <em>tokens</em>   <em>fhir types</em>   <em>intl</em>   <em>utils</em>                  │
   └───────────────────────────────────────────────────────┘

   <b>Data flows one way.</b>   view → query → source → page → model →
   policy → geometry → DOM.   The adapter appears only at the last step,
   and does nothing but own the mount point and marshal cells.
</pre>

<div class="prose">
<h4>The five sentences that define this architecture</h4>
<ol class="claims">
<li><b>The engine has no DOM, no framework and no clinical vocabulary</b>, so it is testable without a renderer
and reusable outside healthcare.</li>
<li><b>The renderer sits below the adapters</b>, so accessibility and virtualisation are written once.</li>
<li><b>An adapter contains no grid logic</b>, and one accessibility-tree assertion run against every adapter is
what makes that enforceable.</li>
<li><b>The healthcare layer sits beside the renderer, never inside the engine</b>, so clinical rules stay
reviewable and non-clinical consumers pay nothing.</li>
<li><b>Everything optional is a package</b>, and a package that is not imported costs zero bytes.</li>
</ol>
</div>
"""


def s_verdict():
    return fill("""
<div class="prose">
<p class="lede2">The question you actually asked is whether this can become something a healthcare enterprise
engineering team evaluates <em>before</em> choosing AG&nbsp;Grid. Here is the honest answer.</p>

<h4>Where the previous design stood, and where this one does</h4>
</div>

@@SCORE@@

<div class="prose">
<h4>The verdict</h4>

<p><b>Build it. Separate repository, framework-agnostic core, React first.</b></p>

<p>The clinical thesis is genuinely differentiated and the category is genuinely open — Terra UI, Cerner's React
design system and the only serious healthcare component library, was archived on 28 June 2024 along with the
entire Cerner GitHub organisation, and nothing has replaced it. There is no healthcare-native grid to compete
with. That is unusual and it will not last indefinitely.</p>

<p>But the previous design would not have produced a library another engineering team evaluates. It would have
produced a very good React table for one product, with a security defect in its export, a physically impossible
performance claim, and a flagship sentence that FHIR cannot support. <b>All three are free to fix today.</b></p>

<h4>Six conditions I would attach</h4>
<ol class="claims">
<li><b>Do not claim framework agnosticism until the second adapter exists.</b> A README listing four frameworks
and supporting one loses precisely the audience it is aimed at.</li>
<li><b>Fix the three security defects before the first export ships.</b> Injection-safe writer, PHI-free
telemetry, renderer safety by type. None is expensive now; all are structural later.</li>
<li><b>Delete the 1M client-side claim and replace it with a refusal.</b> Refusing loudly, with a number and a
reason, builds more credibility than a benchmark table.</li>
<li><b>Decide the licence and support posture before the repository is public.</b> My recommendation is MIT for
everything a security reviewer must read, commercial only for an enterprise recipe pack.</li>
<li><b>Name a clinician reviewer and budget for them before wave three.</b> This is the fourth artefact blocked
on it. Until then every clinical rule here is a well-researched proposal, and should be labelled as one.</li>
<li><b>Keep wave one shippable alone.</b> Six waves is a lot of runway for one person and an agent, and the
architecture must make stopping a decision rather than a failure.</li>
</ol>

<h4>And the one thing I would push back on hardest</h4>
<p>The target you set — a grid that healthcare enterprise teams evaluate before AG&nbsp;Grid — is achievable, but
not by matching AG&nbsp;Grid. It has a decade in its virtualiser and the only mature server-side row model in the
category, and we will not out-build that with the resources available. <b>The way to win the evaluation is to be
the only grid where a clinical safety officer can sign off in an afternoon</b> — because the absence taxonomy,
the coverage declaration, the disclosure policy and the sort provenance are in the types and gated by tests
rather than left to whoever is on the ticket. That is a different axis, it is one AG&nbsp;Grid has no reason to
compete on, and it is worth more to the buyer than pivot mode.</p>

<div class="note">
<p><b>If only one thing from this review survives</b>, make it the framework-free DOM renderer sitting below the
adapters. Everything else in this document can be changed in a later release. That one cannot.</p>
</div>
</div>
""", SCORE=figs.fig_score())
