# -*- coding: utf-8 -*-
"""The healthcare use-case matrix.

Each scenario names the one thing that makes its grid different from a generic
table. `axis` is the grid capability that scenario is the *hardest* test of;
`unit` is what a row actually is, which is the question most grid APIs never
ask. `preset` is the shipped recipe that would serve it.
"""

# family, name, unit-of-a-row, what makes it different, hardest axis, preset, volume
USE_CASES = [
 ("Directory & census", "Patient directory", "a person",
  "Identity is the payload, not a label. Two patients sharing a name must be separated on the row itself, not in a tooltip.",
  "identity", "roster", "10k–2M"),
 ("Directory & census", "Inpatient census", "a person in a bed",
  "Rows arrive and leave while you read. Position must not move under the pointer.",
  "realtime", "census", "40–800"),
 ("Directory & census", "Bed management board", "a bed, occupied or not",
  "The empty rows are the answer. A filter that hides empties destroys the artefact.",
  "absence", "board", "40–1,200"),
 ("Directory & census", "Provider directory", "a practitioner role",
  "One human is several rows — a practitioner has a role per facility, and credentialling differs per row.",
  "grouping", "roster", "500–50k"),
 ("Directory & census", "Care-team roster", "an assignment with a period",
  "Every row is time-bounded. 'Current' is a query, not a column.",
  "temporal", "roster", "5–400"),

 ("Behavioural health", "BH client roster", "a person in a programme",
  "Programme, level of care and consent regime all gate which columns may render at all.",
  "disclosure", "caseload", "50–5k"),
 ("Behavioural health", "CoCM registry", "a person under measurement-based care",
  "The registry is the billable artefact. Caseload review is a required weekly workflow, not a report.",
  "measurement", "registry", "60–300"),
 ("Behavioural health", "Group session roster", "an attendance record",
  "Rows are co-present people. One person's note must not disclose another's attendance.",
  "disclosure", "roster", "4–20"),
 ("Behavioural health", "Crisis / safety follow-up queue", "an obligation with a clock",
  "Overdue is the sort key and the reason for the surface existing.",
  "resolution", "queue", "5–200"),
 ("Behavioural health", "Waitlist", "a person waiting",
  "Ordering is a policy — first-come, acuity, or matched availability — and it must be visible.",
  "sorting", "queue", "50–5k"),
 ("Behavioural health", "Assessment schedule (PHQ-9 / GAD-7)", "a due instrument",
  "The cell is a score with a reliable-change threshold, not a number.",
  "measurement", "registry", "100–10k"),

 ("Clinical work", "Clinical work queue", "an obligation",
  "The row is not a patient — it is a thing owed. Two obligations on one patient are two rows.",
  "resolution", "queue", "20–2k"),
 ("Clinical work", "Results inbox", "a result awaiting acknowledgement",
  "Critical results have a statutory acknowledgement clock and cannot be paged away.",
  "resolution", "queue", "20–1k"),
 ("Clinical work", "Lab results (flowsheet)", "an analyte over time",
  "Columns are time; rows are analytes. The grid is transposed and the header scrolls horizontally.",
  "transpose", "flowsheet", "40 × 200"),
 ("Clinical work", "Vitals flowsheet", "an observation row",
  "Sub-hour columns, dynamic column count, and a value that may be entered later than it was taken.",
  "transpose", "flowsheet", "20 × 2k"),
 ("Clinical work", "Medication list", "an active order",
  "Sig, route and status are one semantic unit; splitting them across columns produces misreads.",
  "cells", "list", "5–120"),
 ("Clinical work", "MAR (administration record)", "a scheduled dose",
  "Cells are time slots that can be acted on. An empty cell is a missed dose, not blank.",
  "transpose", "mar", "20 × 96"),
 ("Clinical work", "Orders", "an order with a lifecycle",
  "Signature state gates every action on the row.",
  "editing", "list", "10–500"),
 ("Clinical work", "Problem list / diagnoses", "a condition with onset",
  "Hierarchy is clinical (SNOMED parentage), not display grouping.",
  "tree", "list", "5–200"),
 ("Clinical work", "Allergies & intolerances", "an assertion",
  "Refuted and entered-in-error rows must remain visible and struck, never deleted.",
  "absence", "list", "0–40"),
 ("Clinical work", "Progress notes / documentation", "a document version",
  "Addenda and amendments are rows about rows.",
  "tree", "list", "50–5k"),
 ("Clinical work", "Care / treatment plan", "a goal with interventions",
  "Genuine tree data with progress aggregation that must not average across incomparable units.",
  "tree", "plan", "10–300"),

 ("Scheduling", "Appointment grid (day/clinic)", "a slot",
  "Two rows may be the same time. Conflict is a first-class render state.",
  "temporal", "schedule", "20–2k"),
 ("Scheduling", "Provider availability", "a bookable window",
  "Rows are generated, not fetched; the row count is a function of the window.",
  "temporal", "schedule", "100–20k"),
 ("Scheduling", "Referral tracking", "a referral in flight",
  "Ageing buckets are the primary lens and they change hourly.",
  "resolution", "queue", "50–5k"),

 ("Revenue & access", "Claims worklist", "a claim line",
  "Money reconciles: group totals must foot exactly and may never be estimated from a page.",
  "aggregation", "ledger", "1k–5M"),
 ("Revenue & access", "Denials & appeals", "a denial with a deadline",
  "Deadline maths drives the sort and drives the money.",
  "resolution", "queue", "100–50k"),
 ("Revenue & access", "Eligibility verification", "a coverage check",
  "Data is fetched per row from a payer that may time out — per-row loading and per-row failure.",
  "realtime", "queue", "50–5k"),
 ("Revenue & access", "Prior authorisations", "an authorisation with units",
  "Units remaining and expiry are the two numbers, and both are derived.",
  "resolution", "queue", "50–10k"),
 ("Revenue & access", "Charge capture / encounters", "a billable encounter",
  "Bulk edit is the whole workflow, and every edit is auditable.",
  "editing", "ledger", "500–500k"),

 ("Population & quality", "Population health cohort", "a person in a denominator",
  "The cohort definition is part of the data. Rows without the definition are meaningless.",
  "coverage", "cohort", "10k–5M"),
 ("Population & quality", "Risk stratification", "a person with a score",
  "Sorting by the score is a triage decision; the model's provenance belongs in the header.",
  "sorting", "cohort", "10k–2M"),
 ("Population & quality", "Quality-measure gaps", "a numerator miss",
  "Exclusions and exceptions are as important as the gap and must be countable.",
  "aggregation", "cohort", "1k–500k"),
 ("Population & quality", "Care-gap outreach", "a person and an attempt",
  "Attempts accumulate on the row and are the reason the row is still open.",
  "resolution", "queue", "1k–200k"),

 ("Operations & governance", "Audit log", "an access event",
  "Append-only, cursor-paged, never sorted client-side, and it is itself evidence.",
  "scale", "ledger", "1M–1B"),
 ("Operations & governance", "Task board", "a task",
  "Assignment changes under you and the assignee may be a pool, not a person.",
  "realtime", "queue", "20–20k"),
 ("Operations & governance", "Secure message queue", "a thread",
  "Unread is per-user state layered over shared data.",
  "realtime", "queue", "20–5k"),
 ("Operations & governance", "ADT feed", "a movement event",
  "Streaming, out-of-order arrival, and corrections that supersede earlier rows.",
  "realtime", "stream", "1k–1M/day"),
 ("Operations & governance", "Device / interface monitor", "a feed's health",
  "The grid is the observability surface for the sources every other grid depends on.",
  "coverage", "board", "10–500"),
]

FAMILIES = []
for u in USE_CASES:
    if u[0] not in FAMILIES:
        FAMILIES.append(u[0])

AXES = {
 "identity":    ("Identity safety", "The row is a person and acting on the wrong one is a reportable event."),
 "realtime":    ("Live data", "Rows change while a human is aiming at them."),
 "absence":     ("Absence semantics", "An empty cell is a fact with a cause, and the causes differ."),
 "grouping":    ("Grouping", "One entity spans rows; the grouping is domain truth, not display."),
 "temporal":    ("Time-bounded rows", "Every row has a period and 'now' is a parameter."),
 "disclosure":  ("Disclosure control", "Which columns may render is a policy evaluation, per row."),
 "measurement": ("Measurement-based care", "Cells are instruments with thresholds, not numbers."),
 "resolution":  ("Resolution", "The row is an obligation: what is owed, by whom, by when."),
 "sorting":     ("Sort provenance", "The sort key is a clinical claim and carries a source."),
 "cells":       ("Composite cells", "Several fields are one semantic unit and must not be split."),
 "transpose":   ("Transposed grids", "Columns are time; the header is the scrolling axis."),
 "editing":     ("Inline editing", "Writes are clinical acts with signature and audit consequences."),
 "tree":        ("Tree data", "Hierarchy is clinical, arrives partial, and aggregates unevenly."),
 "aggregation": ("Aggregation", "Totals must foot exactly and may not be estimated from a page."),
 "coverage":    ("Coverage", "What the query reached is part of the answer."),
 "scale":       ("Scale", "Row counts that make client-side anything impossible."),
}

PRESETS = {
 "roster":    ("Roster",    "People, identity-first, one row per person."),
 "census":    ("Census",    "People in places, live, position-stable."),
 "board":     ("Board",     "Capacity: the empty rows carry the meaning."),
 "caseload":  ("Caseload",  "A clinician's assigned people, disclosure-gated."),
 "registry":  ("Registry",  "Measurement-based care: instruments, due dates, response."),
 "queue":     ("Work queue","Obligations with owners and clocks."),
 "flowsheet": ("Flowsheet", "Transposed: analytes down, time across."),
 "mar":       ("MAR",       "Transposed and actionable: scheduled doses in time slots."),
 "list":      ("Chart list","Short, dense, in-chart lists with composite cells."),
 "plan":      ("Plan",      "Tree data with goals, interventions and progress."),
 "schedule":  ("Schedule",  "Time-bounded bookable rows with conflicts."),
 "ledger":    ("Ledger",    "Money and events: exact totals, server-side everything."),
 "cohort":    ("Cohort",    "Populations with a definition attached."),
 "stream":    ("Stream",    "Append-only, cursor-paged, out-of-order arrival."),
}
