# -*- coding: utf-8 -*-
"""Keyboard model, performance budgets, edge cases, roadmap, open questions."""

# ---------------------------------------------------------------- keyboard
# key, where, what, why-it-differs-from-the-obvious
KEYS = [
 ("Tab / Shift+Tab", "grid", "Move between grid landmarks: toolbar → filter bar → grid body → pagination.",
  "The body is ONE tab stop. A 40×20 grid with a tab stop per cell is 800 presses to leave."),
 ("Arrow keys", "cell", "Move the focused cell by one.", ""),
 ("Home / End", "cell", "First / last cell in the row.", ""),
 ("Ctrl+Home / Ctrl+End", "cell", "First cell of the first row / last cell of the last row.",
  "Under virtualisation this must fetch, not clamp to the loaded window."),
 ("Page Up / Page Down", "cell", "Move by one viewport of rows.", ""),
 ("Enter", "cell", "Activate the cell's primary action, or begin editing an editable cell.", ""),
 ("F2", "cell", "Begin editing without activating.", "Enter is overloaded on action cells; F2 is unambiguous."),
 ("Escape", "editor", "Cancel the edit and restore the previous value; focus returns to the cell.", ""),
 ("Space", "row", "Toggle selection of the focused row.", ""),
 ("Shift+Space", "cell", "Select the focused row from a cell.", ""),
 ("Shift+↑ / Shift+↓", "row", "Extend the selection.", ""),
 ("Ctrl+A", "grid", "Select every row on this page, and say so in the live region.",
  "It must NOT mean 'select all 240,000 matching rows'. That is a separate, explicit affordance."),
 ("Ctrl+Space", "cell", "Select the focused column (range plugin).", ""),
 ("Alt+↓ on a header", "header", "Open that column's menu.", ""),
 ("Enter on a header", "header", "Sort. Repeated presses cycle ascending → descending → none.",
  "The 'none' state must be reachable: a grid you cannot un-sort has lost its default order."),
 ("Shift+Enter on a header", "header", "Add this column to the sort as the next precedence.", ""),
 ("Ctrl+Alt+← / →", "header", "Move the column.", "Not a drag-only affordance; reorder is a keyboard operation."),
 ("Ctrl+Alt+Shift+← / →", "header", "Resize the column by one step.", ""),
 ("→ on a collapsed group or tree row", "row", "Expand.", ""),
 ("← on an expanded row", "row", "Collapse; on an already-collapsed child, move to the parent.", ""),
 ("Ctrl+C", "grid", "Copy the selection as it appears, masks included.",
  "Copy must never un-mask. The clipboard leaves the audited surface."),
 ("/ or Ctrl+K", "grid", "Focus search / open the command palette.", ""),
 ("Escape", "grid", "Clear the search box; a second press clears the focused filter chip.", ""),
 ("Alt+N", "grid", "Jump to the arrivals divider — 'what is new since I looked'.",
  "Arrivals never insert under the pointer, so there must be a way to go to them."),
]

# --------------------------------------------------------------- perf
# rows, mode, first-paint budget, sort budget, filter/keystroke budget, scroll, memory
PERF = [
 ("100",        "client, no virtualisation",  "≤ 80 ms",  "≤ 16 ms", "≤ 16 ms", "n/a",             "< 2 MB"),
 ("1,000",      "client, virtualised rows",   "≤ 120 ms", "≤ 40 ms", "≤ 32 ms", "60 fps",          "< 8 MB"),
 ("10,000",     "client, virtualised both",   "≤ 180 ms", "≤ 120 ms","≤ 50 ms", "60 fps",          "< 40 MB"),
 ("100,000",    "server sort/filter, windowed","≤ 200 ms","server",  "≤ 50 ms local echo","60 fps","< 60 MB"),
 ("1,000,000+", "server everything, cursor",  "≤ 200 ms", "server",  "≤ 50 ms local echo","60 fps","< 60 MB"),
]

PERF_RULES = [
 ("Every interaction budget is an INP budget.",
  "A good Interaction to Next Paint is ≤ 200 ms at the 75th percentile; 43% of sites still fail it, and it is now the most commonly failed Core Web Vital. Our per-interaction numbers above sit well inside it so that the grid is never the reason a page fails."),
 ("Budgets are asserted in CI, not measured once.",
  "A Playwright benchmark renders the fixed 10k and 100k fixtures on a CPU-throttled profile and fails the build on regression, in the same way `size-limit` already guards installed bytes."),
 ("The row count above which client-side operations are refused is a constant, not a vibe.",
  "Past it, `mode=\"client\"` throws in development and degrades to server mode in production, because a silently 4-second sort is worse than a clear error."),
 ("Memory is a budget because clinical workstations are not developer laptops.",
  "A shared workstation runs the EHR, two portals and this grid in one browser profile with 4 GB and a decade-old CPU."),
]

# --------------------------------------------------------------- edge cases
# id, scenario, what a normal grid does, what ours must do, severity
EDGES = [
 ("dup-name", "Two patients on the roster share a name and a date of birth (twins).",
  "Renders two identical-looking rows.",
  "`disambiguate()` adds the minimum that separates them — full given name, then DOB, then identifier — and the row renders it inline.", "critical"),
 ("sort-under", "A new admission arrives while the user is moving the pointer toward row 4.",
  "Re-sorts; the click lands on a different patient.",
  "Sort position freezes while a pointer or focus is inside the body. The arrival queues behind an arrivals divider.", "critical"),
 ("filter-zero", "A filter is left on from yesterday and today's query returns nothing.",
  "Renders 'No data'.",
  "Renders the predicate in words plus 'no rows match this query' — a different sentence from 'this list is empty'.", "critical"),
 ("source-down", "One of four data sources times out.",
  "Renders the three that answered, cleanly.",
  "Renders them AND escalates the failure to `role=\"alert\"`, because the reader is about to convert an absence into a clinical fact.", "critical"),
 ("mask-export", "A masked cell is exported to CSV.",
  "Exports the underlying value, because the mask was a render concern.",
  "Exports the mask. Un-masking in an export requires the same authorisation as un-masking on screen, and emits a disclosure event.", "critical"),
 ("bulk-stale", "A bulk action is confirmed against a selection built four minutes ago.",
  "Applies to the ids, whatever they now are.",
  "Re-resolves the selection, shows what changed, and requires re-confirmation if any row left the predicate.", "critical"),
 ("select-all-predicate", "'Select all' with 240,000 matching rows.",
  "Selects the 50 on screen, or silently selects everything.",
  "Two distinct affordances, two distinct sentences, and the predicate travels with the action instead of an id list.", "high"),
 ("range-missing", "A lab result has no reference range.",
  "Renders the number, which reads as normal.",
  "Renders the number as explicitly uninterpreted. `ResultValue` already refuses to imply normality.", "critical"),
 ("unit-change", "The assay changed mid-series, so the units differ across a trend.",
  "Draws one continuous sparkline.",
  "Breaks the series and says why. `TrendIndicator` already has `AssayChange` and `UnitChange` states.", "high"),
 ("tz-midnight", "A night-shift worklist crosses midnight in a facility on a different offset.",
  "Buckets by the browser's local day.",
  "Buckets by the facility's day, and a row's day never depends on where the reader is sitting.", "high"),
 ("dst", "A 2 am medication administration on the day the clock goes back.",
  "Shows one row; the duplicated hour is lost.",
  "Renders both occurrences with their offsets. The MAR grid's column axis is instants, not wall-clock labels.", "high"),
 ("partial-tree", "A care-plan tree returns two levels; the third has not loaded.",
  "Renders a leaf.",
  "Renders an unresolved branch. A node with unknown children is not a node with no children.", "high"),
 ("agg-mixed", "A group summary spans rows in mmol/L and mg/dL.",
  "Sums them.",
  "Refuses, and says the units are incomparable.", "critical"),
 ("row-height-jump", "A cell's content grows after measurement — a chip row wraps at 90% zoom.",
  "Scroll position jumps.",
  "Heights are measured and cached per row; a re-measure adjusts scrollTop to keep the anchor row still.", "high"),
 ("zoom-200", "200% zoom on a 1280px laptop.",
  "Horizontal scroll for the whole page.",
  "The grid reflows to its column priority; the page never scrolls horizontally, only the grid's own scroller does.", "high"),
 ("forced-colors", "Windows high-contrast mode.",
  "Every status becomes the same colour and the meaning is gone.",
  "Status carries glyph and text; the contrast gate and forced-colors tests already run in three engines.", "high"),
 ("rtl", "An Arabic locale.",
  "Pinned columns pin to the wrong side.",
  "Pinning is logical (`inline-start`/`inline-end`), and the identity column pins to the reading start.", "medium"),
 ("print-1200", "A 1,200-row worklist sent to a printer.",
  "Prints page one, or 1,200 rows with no header.",
  "Prints the coverage sentence and the predicate on every page, repeats the header row, and states the row range on each sheet.", "high"),
 ("session-expiry", "The session expires with an unsaved inline edit.",
  "The edit is lost on re-auth.",
  "The edit is held in the commit phase, the grid restores its view after re-auth, and the pending write is re-offered — never silently replayed.", "high"),
 ("concurrent-edit", "Two clinicians edit the same row's status.",
  "Last write wins.",
  "The second write is refused with both values shown and no preselection — the same rule as the Switch's `stale` state.", "critical"),
 ("ws-flood", "A WebSocket delivers 400 updates in two seconds during a code.",
  "400 re-renders.",
  "Updates coalesce on an animation frame, and the arrivals counter is the only thing that moves.", "high"),
 ("ws-out-of-order", "An ADT correction arrives before the event it corrects.",
  "The correction is applied, then overwritten by the stale event.",
  "Rows carry a version; an older version is dropped, not applied.", "high"),
 ("perm-change", "A user's role changes while the grid is open.",
  "Columns keep rendering from cached data.",
  "The disclosure policy is re-evaluated, columns disappear, and the grid states that the view changed.", "critical"),
 ("id-collision", "Two source systems supply rows with the same local id.",
  "React reconciles them into one row.",
  "`rowKey` is required to be a stable, source-qualified identity; a duplicate key is a development error, not a silent merge.", "critical"),
 ("empty-vs-zero", "A count column where the value is genuinely 0 versus not measured.",
  "Both render as `0` or both as blank.",
  "Zero is zero; not-measured is a typed absence with a reason.", "critical"),
 ("very-long-cell", "A 4,000-character free-text note in a cell.",
  "Breaks the row height or is silently cut.",
  "Truncates with a visible, keyboard-reachable expansion, and the export carries the whole value.", "medium"),
 ("no-mouse", "A clinician on a workstation with a broken trackpad.",
  "Column resize, reorder and range selection are unreachable.",
  "Every grid operation has a keyboard path; that is asserted by a test that never dispatches a pointer event.", "high"),
 ("sr-virtual", "A screen-reader user on a 40,000-row grid.",
  "Announces 'row 1 of 20' forever.",
  "`aria-rowcount` is the full count; `aria-rowindex` is absolute; the loading window is announced politely.", "critical"),
]

# --------------------------------------------------------------- roadmap
ROADMAP = [
 {
  "n": 1, "name": "Foundation", "weeks": "3–4",
  "goal": "A grid you could ship a patient directory on, that already tells the truth.",
  "components": ["grid-core", "DataGrid", "DataGridToolbar", "DataGridColumnHeader", "DataGridRow", "DataGridCell", "DataGridPagination", "DataGridEmpty", "DataGridSkeleton", "GridCoverage"],
  "tasks": [
    "Column model, row model, and the reducer that owns sort · filter · selection · pagination.",
    "The antd `Table` props-parity surface: `columns`, `dataSource`, `rowKey`, `rowSelection`, `pagination`, `onChange`.",
    "`role=\"grid\"` with a roving cell focus and the full arrow/Home/End/PageUp model.",
    "Required `coverage`, the six empty states, and the predicate sentence.",
    "Density as a token axis over the three that already exist, plus `ultra`.",
  ],
  "deps": ["@oxygenui-design/tokens", "@oxygenui-design/intl", "existing clinical primitives for the demo columns"],
  "risks": ["The keyboard model is the part most likely to be wrong, and it is the part hardest to change later."],
  "tests": ["Every operation driven by keyboard only, never dispatching a pointer event.", "axe across 3 themes × 4 densities.", "Props-parity table against antd 6.x so a rename in an antd major fails our build."],
  "accept": "A 500-row roster, operated end-to-end with the keyboard, passing axe in three engines, that renders its coverage sentence in print.",
 },
 {
  "n": 2, "name": "Scale", "weeks": "3–4",
  "goal": "The same grid at a million rows without changing a line of consumer code.",
  "components": ["DataGridVirtualizer", "DataGridScroller", "useServerRows", "DataGridFilterBar", "FilterBuilder"],
  "tasks": [
    "Row and column virtualisation with measured, cached heights and anchor-stable re-measure.",
    "Absolute `aria-rowindex` / `aria-colindex` and `aria-rowcount` under windowing.",
    "The server contract: one `GridQuery` in, one `GridPage` out, with cursors.",
    "Request cancellation, debounce, prefetch on scroll velocity, and a typed cache key.",
    "The filter AST plus the visual builder and the chip bar over it.",
  ],
  "deps": ["Phase 1"],
  "risks": ["Sticky columns × virtualisation is where antd's implementation still has a layout defect; ours needs a test that would catch it.",
            "Dynamic row heights and scroll anchoring is the single hardest engineering problem in the whole component."],
  "tests": ["CPU-throttled benchmark at 10k and 100k asserting the budgets in §Performance.", "A screen-reader announcement test at row 19,998 of 40,000."],
  "accept": "100,000 rows, server-sorted, scrolled at 60 fps, announcing absolute positions, with every budget asserted in CI.",
 },
 {
  "n": 3, "name": "Clinical shape", "weeks": "4–5",
  "goal": "The grid stops being a table and starts being a worklist.",
  "components": ["GridIdentityCell", "GridResolutionCell", "GridStatusCell", "GridResultCell", "GridMedicationCell", "GridAppointmentCell", "GridChipOverflow", "GridArrivals", "GridSortProvenance"],
  "tasks": [
    "The cell host contract: measurement, truncation, focus delegation, print and export behaviour, so the shipped primitives drop in unchanged.",
    "Grouping, tree data, aggregation with unit refusal, and group summaries.",
    "Frozen sort under the pointer, the arrivals queue, changed-cell attention and the stale indicator.",
    "Sort provenance in the header for derived and model columns.",
    "Transposed mode (flowsheet / MAR).",
  ],
  "deps": ["Phase 2", "clinical-status", "result-value", "risk-indicator", "allergy-chip", "trend-indicator", "provenance-chip", "identity"],
  "risks": ["Transposed mode may want to be a second component; the decision belongs at the end of this phase, on evidence."],
  "tests": ["A property test that a live update never changes the index of the row under the pointer.",
            "Aggregation refuses mixed units — asserted in words, not by an exception type."],
  "accept": "The behavioural-health caseload and the results inbox both built from recipes, with no bespoke cell code.",
 },
 {
  "n": 4, "name": "Work", "weeks": "4–5",
  "goal": "Doing something to many people, safely.",
  "components": ["DataGridSelectionBar", "BulkReview", "DataGridInspector", "DataGridEditor", "SavedViews", "ColumnPanel", "GridExport", "GridPrintSheet"],
  "tasks": [
    "Selection as ids-plus-predicate, and the two distinct select-all affordances.",
    "The bulk review step that names the people before the write runs.",
    "The inspector: grid keeps focus context, panel takes the detail, one URL.",
    "Inline and row editing over `useCommitPhase()`, with optimistic update and typed rollback.",
    "`GridView` as a serialisable document, and the default → role → team → personal precedence.",
    "Export and print, both carrying the coverage sentence and the predicate.",
  ],
  "deps": ["Phase 3"],
  "risks": ["Saved views are where a schema mistake becomes a migration; version the document from the first commit."],
  "tests": ["A stale-selection test: rows leave the predicate between selection and confirmation.",
            "An export test asserting a masked cell exports masked."],
  "accept": "A 12-patient bulk reassignment that shows the twelve, survives one of them leaving the predicate, and writes an export that a compliance officer can read.",
 },
 {
  "n": 5, "name": "Disclosure", "weeks": "3–4",
  "goal": "The grid participates in minimum-necessary instead of ignoring it.",
  "components": ["useDisclosurePolicy", "GridMaskedCell", "GridRestrictedRow", "BreakGlassPrompt", "GridDisclosureEvents"],
  "tasks": [
    "One policy evaluation feeding column visibility, cell masking, row restriction and break-glass.",
    "A column the viewer may not see is absent AND its absence is stated — never silently dropped.",
    "Break-glass reason capture, with the decision left to the server.",
    "Disclosure events emitted for view, expand, export, print and copy.",
    "Re-evaluation on permission change while the grid is open.",
  ],
  "deps": ["Phase 4", "the Access & Disclosure Kernel from the healthcare-50 brief"],
  "risks": ["This is the phase most likely to be mistaken for a compliance guarantee. The `limitations` copy has to be written before the code."],
  "tests": ["A permission-change test that asserts columns disappear and the change is announced.",
            "A copy test asserting the clipboard carries the mask."],
  "accept": "One policy object drives six behaviours, and a 42 CFR Part 2-segmented row renders correctly in all four roles.",
 },
 {
  "n": 6, "name": "Intelligence", "weeks": "3–4",
  "goal": "AI that is legible as AI.",
  "components": ["NLFilterBar", "GridProposal", "GridRowSummary", "GridAnomalyMark"],
  "tasks": [
    "Natural language compiles to the same `FilterNode` AST and renders as chips BEFORE it runs.",
    "A proposal channel — proposed columns, groupings and filters — that never writes.",
    "Row summaries carrying provenance and confidence, using the AI states the primitives already have.",
    "Anomaly marks that are a lens, never a sort default.",
  ],
  "deps": ["Phase 5", "copilot-core"],
  "risks": ["An AI-generated filter that silently narrows a cohort is the single most dangerous thing in this document."],
  "tests": ["An NL query that cannot be compiled must fail visibly rather than approximating.",
            "AI-derived values must never satisfy the same assertion as a verified value."],
  "accept": "Every AI output on the surface is distinguishable from verified data without colour, and no AI path can mutate data.",
 },
 {
  "n": 7, "name": "Hardening & documentation", "weeks": "3",
  "goal": "The gates, not the features.",
  "components": ["docs page", "grid-testing package", "fixtures"],
  "tasks": [
    "Screen-reader matrix: NVDA, JAWS, VoiceOver × Chromium, Firefox, WebKit.",
    "Visual regression across 3 themes × 4 densities × the recipes.",
    "Benchmarks wired into CI with a ratchet.",
    "The documentation page, generated from the schema like every other component page.",
    "`@oxygenui-design/grid-testing`: assertions that read a grid's accessibility tree, matching the `tabs-testing` precedent.",
  ],
  "deps": ["Phases 1–6"],
  "risks": ["The screen-reader matrix is the one thing here that cannot be automated and is the gate on leaving `experimental`."],
  "tests": ["Everything above, running on every pull request."],
  "accept": "The component moves off `experimental` because a matrix says it may, not because it feels done.",
 },
]

# ------------------------------------------------------- open questions
OPEN = [
 ("Is the grid free or the first paid pack?",
  "The catalogue is currently 100% `tier: \"free\"` and the marketplace prices packs, not components. A data grid is the single most valuable thing in this library and the most expensive to build — roughly 23–29 weeks by the plan above. My recommendation: **the engine, the presentation layer, the keyboard model and the whole safety surface are free forever; the paid pack is the recipes** (MAR, flowsheet, claims ledger, cohort) plus `grid-testing`. It keeps the SEO and trust value, and it prices the part that is genuinely bespoke labour.",
  "recommend"),
 ("Does `coverage` stay required here?",
  "ADR 0011 says yes and the grid is the case the ADR was actually about. But a grid is a far more common surface than a timeline, and this is the prop most likely to make someone choose a different library. My recommendation: **required, no escape hatch**, same as `CareTimeline` — but ship a `coverage.local()` helper for the honest single-source case so the minimum is one line rather than four.",
  "recommend"),
 ("Is the transposed grid the same component?",
  "Flowsheet and MAR invert the axes: analytes down, time across, header scrolling. That is either a `layout` prop or a second component. My recommendation: **one component, `layout=\"transposed\"`**, decided at the end of Phase 3 on evidence — but I want the decision recorded as provisional, because getting it wrong is a public API break.",
  "recommend"),
 ("What is the row-count constant past which client mode refuses?",
  "I have written it as a constant rather than a judgement call, which is right, but I have not chosen the number. It should be measured on the CI machine at the density where the budget breaks, not picked. Blocking on Phase 2's benchmark.",
  "blocked"),
 ("Do we take a dependency on TanStack Table v9 for the engine?",
  "It is MIT, modular, ~25 KB, and genuinely good — and v9's memory work is exactly our problem. Against: ADR 0009's supply-chain constraints, copy-source distribution needs self-contained files, and our row model has to carry disclosure and absence semantics that its row model has no place for. My recommendation: **no dependency, but read its row-model pipeline closely** — the same conclusion ADR 0010 reached about rc-switch, for the same reason.",
  "recommend"),
 ("Who is the named clinician reviewer, and at what rate?",
  "This is the third brief to ask. It now blocks the behavioural-health recipes, the MAR, and the safety copy in Phase 5 — all of which state clinical rules I derived from literature rather than from a clinician's screen.",
  "blocked"),
 ("Does the grid own search, or compose `ChartCommandPalette`?",
  "The palette already ships and already solves scoped search, frequency weighting and the out-of-scope count. My recommendation: **compose it**, and let the grid's own search box be the narrow, in-place one. Two search surfaces with different behaviour would be worse than either.",
  "recommend"),
 ("Is `DataGrid` the right name given ADR 0010?",
  "antd's component is `Table`. Ours matches its API but is not it — it is `role=\"grid\"`, cell-focusable and virtualised by default. Shipping a `Table` that behaves differently from antd's `Table` would break the parity promise. My recommendation: **`DataGrid`**, with the props-parity table asserted against antd's `Table` and the divergences named in `limitations` — and a one-line codemod in `@oxygenui-design/codemod` for people migrating from antd.",
  "recommend"),
]
